// @generated by protobuf-ts 2.8.1 with parameter output_typescript
// @generated from protobuf file "AbilityMetaSpecialFloatArgument.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message AbilityMetaSpecialFloatArgument
 */
export interface AbilityMetaSpecialFloatArgument {
    /**
     * @generated from protobuf field: float argument_value = 4;
     */
    argumentValue: number;
    /**
     * @generated from protobuf field: bool is_on = 10;
     */
    isOn: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class AbilityMetaSpecialFloatArgument$Type extends MessageType<AbilityMetaSpecialFloatArgument> {
    constructor() {
        super("AbilityMetaSpecialFloatArgument", [
            { no: 4, name: "argument_value", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 10, name: "is_on", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<AbilityMetaSpecialFloatArgument>): AbilityMetaSpecialFloatArgument {
        const message = { argumentValue: 0, isOn: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AbilityMetaSpecialFloatArgument>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AbilityMetaSpecialFloatArgument): AbilityMetaSpecialFloatArgument {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* float argument_value */ 4:
                    message.argumentValue = reader.float();
                    break;
                case /* bool is_on */ 10:
                    message.isOn = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AbilityMetaSpecialFloatArgument, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* float argument_value = 4; */
        if (message.argumentValue !== 0)
            writer.tag(4, WireType.Bit32).float(message.argumentValue);
        /* bool is_on = 10; */
        if (message.isOn !== false)
            writer.tag(10, WireType.Varint).bool(message.isOn);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AbilityMetaSpecialFloatArgument
 */
export const AbilityMetaSpecialFloatArgument = new AbilityMetaSpecialFloatArgument$Type();
