// @generated by protobuf-ts 2.8.2 with parameter output_typescript
// @generated from protobuf file "ActivityScheduleInfo.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ActivityScheduleInfo
 */
export interface ActivityScheduleInfo {
    /**
     * @generated from protobuf field: uint32 end_time = 3;
     */
    endTime: number;
    /**
     * @generated from protobuf field: bool is_open = 12;
     */
    isOpen: boolean;
    /**
     * @generated from protobuf field: uint32 begin_time = 1;
     */
    beginTime: number;
    /**
     * @generated from protobuf field: uint32 schedule_id = 9;
     */
    scheduleId: number;
    /**
     * @generated from protobuf field: uint32 activity_id = 11;
     */
    activityId: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class ActivityScheduleInfo$Type extends MessageType<ActivityScheduleInfo> {
    constructor() {
        super("ActivityScheduleInfo", [
            { no: 3, name: "end_time", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 12, name: "is_open", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 1, name: "begin_time", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 9, name: "schedule_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "activity_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ActivityScheduleInfo>): ActivityScheduleInfo {
        const message = { endTime: 0, isOpen: false, beginTime: 0, scheduleId: 0, activityId: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ActivityScheduleInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ActivityScheduleInfo): ActivityScheduleInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 end_time */ 3:
                    message.endTime = reader.uint32();
                    break;
                case /* bool is_open */ 12:
                    message.isOpen = reader.bool();
                    break;
                case /* uint32 begin_time */ 1:
                    message.beginTime = reader.uint32();
                    break;
                case /* uint32 schedule_id */ 9:
                    message.scheduleId = reader.uint32();
                    break;
                case /* uint32 activity_id */ 11:
                    message.activityId = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ActivityScheduleInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 end_time = 3; */
        if (message.endTime !== 0)
            writer.tag(3, WireType.Varint).uint32(message.endTime);
        /* bool is_open = 12; */
        if (message.isOpen !== false)
            writer.tag(12, WireType.Varint).bool(message.isOpen);
        /* uint32 begin_time = 1; */
        if (message.beginTime !== 0)
            writer.tag(1, WireType.Varint).uint32(message.beginTime);
        /* uint32 schedule_id = 9; */
        if (message.scheduleId !== 0)
            writer.tag(9, WireType.Varint).uint32(message.scheduleId);
        /* uint32 activity_id = 11; */
        if (message.activityId !== 0)
            writer.tag(11, WireType.Varint).uint32(message.activityId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ActivityScheduleInfo
 */
export const ActivityScheduleInfo = new ActivityScheduleInfo$Type();
