/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: AskAddFriendRsp.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class AskAddFriendRsp extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        param?: number;
        retcode?: number;
        target_uid?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("param" in data && data.param != undefined) {
                this.param = data.param;
            }
            if ("retcode" in data && data.retcode != undefined) {
                this.retcode = data.retcode;
            }
            if ("target_uid" in data && data.target_uid != undefined) {
                this.target_uid = data.target_uid;
            }
        }
    }
    get param() {
        return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
    }
    set param(value: number) {
        pb_1.Message.setField(this, 8, value);
    }
    get retcode() {
        return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
    }
    set retcode(value: number) {
        pb_1.Message.setField(this, 7, value);
    }
    get target_uid() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set target_uid(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        param?: number;
        retcode?: number;
        target_uid?: number;
    }): AskAddFriendRsp {
        const message = new AskAddFriendRsp({});
        if (data.param != null) {
            message.param = data.param;
        }
        if (data.retcode != null) {
            message.retcode = data.retcode;
        }
        if (data.target_uid != null) {
            message.target_uid = data.target_uid;
        }
        return message;
    }
    toObject() {
        const data: {
            param?: number;
            retcode?: number;
            target_uid?: number;
        } = {};
        if (this.param != null) {
            data.param = this.param;
        }
        if (this.retcode != null) {
            data.retcode = this.retcode;
        }
        if (this.target_uid != null) {
            data.target_uid = this.target_uid;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.param != 0)
            writer.writeUint32(8, this.param);
        if (this.retcode != 0)
            writer.writeInt32(7, this.retcode);
        if (this.target_uid != 0)
            writer.writeUint32(4, this.target_uid);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AskAddFriendRsp {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AskAddFriendRsp();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 8:
                    message.param = reader.readUint32();
                    break;
                case 7:
                    message.retcode = reader.readInt32();
                    break;
                case 4:
                    message.target_uid = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): AskAddFriendRsp {
        return AskAddFriendRsp.deserialize(bytes);
    }
}
