"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _BattlePassBuySuccNotify_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.BattlePassBuySuccNotify = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: BattlePassBuySuccNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const dependency_1 = require("./ItemParam");
const pb_1 = require("google-protobuf");
class BattlePassBuySuccNotify extends pb_1.Message {
    constructor(data) {
        super();
        _BattlePassBuySuccNotify_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [9], __classPrivateFieldGet(this, _BattlePassBuySuccNotify_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("schedule_id" in data && data.schedule_id != undefined) {
                this.schedule_id = data.schedule_id;
            }
            if ("product_play_type" in data && data.product_play_type != undefined) {
                this.product_play_type = data.product_play_type;
            }
            if ("add_point" in data && data.add_point != undefined) {
                this.add_point = data.add_point;
            }
            if ("item_list" in data && data.item_list != undefined) {
                this.item_list = data.item_list;
            }
        }
    }
    get schedule_id() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0);
    }
    set schedule_id(value) {
        pb_1.Message.setField(this, 4, value);
    }
    get product_play_type() {
        return pb_1.Message.getFieldWithDefault(this, 11, 0);
    }
    set product_play_type(value) {
        pb_1.Message.setField(this, 11, value);
    }
    get add_point() {
        return pb_1.Message.getFieldWithDefault(this, 12, 0);
    }
    set add_point(value) {
        pb_1.Message.setField(this, 12, value);
    }
    get item_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.ItemParam, 9);
    }
    set item_list(value) {
        pb_1.Message.setRepeatedWrapperField(this, 9, value);
    }
    static fromObject(data) {
        const message = new BattlePassBuySuccNotify({});
        if (data.schedule_id != null) {
            message.schedule_id = data.schedule_id;
        }
        if (data.product_play_type != null) {
            message.product_play_type = data.product_play_type;
        }
        if (data.add_point != null) {
            message.add_point = data.add_point;
        }
        if (data.item_list != null) {
            message.item_list = data.item_list.map(item => dependency_1.ItemParam.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.schedule_id != null) {
            data.schedule_id = this.schedule_id;
        }
        if (this.product_play_type != null) {
            data.product_play_type = this.product_play_type;
        }
        if (this.add_point != null) {
            data.add_point = this.add_point;
        }
        if (this.item_list != null) {
            data.item_list = this.item_list.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.schedule_id != 0)
            writer.writeUint32(4, this.schedule_id);
        if (this.product_play_type != 0)
            writer.writeUint32(11, this.product_play_type);
        if (this.add_point != 0)
            writer.writeUint32(12, this.add_point);
        if (this.item_list.length)
            writer.writeRepeatedMessage(9, this.item_list, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BattlePassBuySuccNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 4:
                    message.schedule_id = reader.readUint32();
                    break;
                case 11:
                    message.product_play_type = reader.readUint32();
                    break;
                case 12:
                    message.add_point = reader.readUint32();
                    break;
                case 9:
                    reader.readMessage(message.item_list, () => pb_1.Message.addToRepeatedWrapperField(message, 9, dependency_1.ItemParam.deserialize(reader), dependency_1.ItemParam));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return BattlePassBuySuccNotify.deserialize(bytes);
    }
}
exports.BattlePassBuySuccNotify = BattlePassBuySuccNotify;
_BattlePassBuySuccNotify_one_of_decls = new WeakMap();
