"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _BeginCameraSceneLookNotify_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.BeginCameraSceneLookNotify = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: BeginCameraSceneLookNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const dependency_1 = require("./Vector");
const pb_1 = require("google-protobuf");
class BeginCameraSceneLookNotify extends pb_1.Message {
    constructor(data) {
        super();
        _BeginCameraSceneLookNotify_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], __classPrivateFieldGet(this, _BeginCameraSceneLookNotify_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("Unk3000_MNLLCJMPMNH" in data && data.Unk3000_MNLLCJMPMNH != undefined) {
                this.Unk3000_MNLLCJMPMNH = data.Unk3000_MNLLCJMPMNH;
            }
            if ("Unk2700_DHAHEKOGHBJ" in data && data.Unk2700_DHAHEKOGHBJ != undefined) {
                this.Unk2700_DHAHEKOGHBJ = data.Unk2700_DHAHEKOGHBJ;
            }
            if ("is_set_screen_xy" in data && data.is_set_screen_xy != undefined) {
                this.is_set_screen_xy = data.is_set_screen_xy;
            }
            if ("look_pos" in data && data.look_pos != undefined) {
                this.look_pos = data.look_pos;
            }
            if ("is_recover_keep_current" in data && data.is_recover_keep_current != undefined) {
                this.is_recover_keep_current = data.is_recover_keep_current;
            }
            if ("Unk3000_GOPIFPMFEPB" in data && data.Unk3000_GOPIFPMFEPB != undefined) {
                this.Unk3000_GOPIFPMFEPB = data.Unk3000_GOPIFPMFEPB;
            }
            if ("Unk2700_HIAKNNCKHJB" in data && data.Unk2700_HIAKNNCKHJB != undefined) {
                this.Unk2700_HIAKNNCKHJB = data.Unk2700_HIAKNNCKHJB;
            }
            if ("is_change_play_mode" in data && data.is_change_play_mode != undefined) {
                this.is_change_play_mode = data.is_change_play_mode;
            }
            if ("Unk3000_IEFIKMHCKDH" in data && data.Unk3000_IEFIKMHCKDH != undefined) {
                this.Unk3000_IEFIKMHCKDH = data.Unk3000_IEFIKMHCKDH;
            }
            if ("screen_y" in data && data.screen_y != undefined) {
                this.screen_y = data.screen_y;
            }
            if ("is_set_follow_pos" in data && data.is_set_follow_pos != undefined) {
                this.is_set_follow_pos = data.is_set_follow_pos;
            }
            if ("is_force" in data && data.is_force != undefined) {
                this.is_force = data.is_force;
            }
            if ("Unk3000_OGCLMFFADBD" in data && data.Unk3000_OGCLMFFADBD != undefined) {
                this.Unk3000_OGCLMFFADBD = data.Unk3000_OGCLMFFADBD;
            }
            if ("entity_id" in data && data.entity_id != undefined) {
                this.entity_id = data.entity_id;
            }
            if ("screen_x" in data && data.screen_x != undefined) {
                this.screen_x = data.screen_x;
            }
            if ("is_force_walk" in data && data.is_force_walk != undefined) {
                this.is_force_walk = data.is_force_walk;
            }
            if ("other_params" in data && data.other_params != undefined) {
                this.other_params = data.other_params;
            }
            if ("follow_pos" in data && data.follow_pos != undefined) {
                this.follow_pos = data.follow_pos;
            }
            if ("is_allow_input" in data && data.is_allow_input != undefined) {
                this.is_allow_input = data.is_allow_input;
            }
            if ("duration" in data && data.duration != undefined) {
                this.duration = data.duration;
            }
        }
    }
    get Unk3000_MNLLCJMPMNH() {
        return pb_1.Message.getFieldWithDefault(this, 1154, 0);
    }
    set Unk3000_MNLLCJMPMNH(value) {
        pb_1.Message.setField(this, 1154, value);
    }
    get Unk2700_DHAHEKOGHBJ() {
        return pb_1.Message.getFieldWithDefault(this, 7, 0);
    }
    set Unk2700_DHAHEKOGHBJ(value) {
        pb_1.Message.setField(this, 7, value);
    }
    get is_set_screen_xy() {
        return pb_1.Message.getFieldWithDefault(this, 5, false);
    }
    set is_set_screen_xy(value) {
        pb_1.Message.setField(this, 5, value);
    }
    get look_pos() {
        return pb_1.Message.getWrapperField(this, dependency_1.Vector, 4);
    }
    set look_pos(value) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_look_pos() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get is_recover_keep_current() {
        return pb_1.Message.getFieldWithDefault(this, 11, false);
    }
    set is_recover_keep_current(value) {
        pb_1.Message.setField(this, 11, value);
    }
    get Unk3000_GOPIFPMFEPB() {
        return pb_1.Message.getFieldWithDefault(this, 1375, false);
    }
    set Unk3000_GOPIFPMFEPB(value) {
        pb_1.Message.setField(this, 1375, value);
    }
    get Unk2700_HIAKNNCKHJB() {
        return pb_1.Message.getFieldWithDefault(this, 6, BeginCameraSceneLookNotify.Unk2700_LNCHDDOOECD.Unk2700_LNCHDDOOECD_Unk2700_ACOENBMDFBP);
    }
    set Unk2700_HIAKNNCKHJB(value) {
        pb_1.Message.setField(this, 6, value);
    }
    get is_change_play_mode() {
        return pb_1.Message.getFieldWithDefault(this, 9, false);
    }
    set is_change_play_mode(value) {
        pb_1.Message.setField(this, 9, value);
    }
    get Unk3000_IEFIKMHCKDH() {
        return pb_1.Message.getFieldWithDefault(this, 1103, 0);
    }
    set Unk3000_IEFIKMHCKDH(value) {
        pb_1.Message.setField(this, 1103, value);
    }
    get screen_y() {
        return pb_1.Message.getFieldWithDefault(this, 15, 0);
    }
    set screen_y(value) {
        pb_1.Message.setField(this, 15, value);
    }
    get is_set_follow_pos() {
        return pb_1.Message.getFieldWithDefault(this, 13, false);
    }
    set is_set_follow_pos(value) {
        pb_1.Message.setField(this, 13, value);
    }
    get is_force() {
        return pb_1.Message.getFieldWithDefault(this, 12, false);
    }
    set is_force(value) {
        pb_1.Message.setField(this, 12, value);
    }
    get Unk3000_OGCLMFFADBD() {
        return pb_1.Message.getFieldWithDefault(this, 1758, 0);
    }
    set Unk3000_OGCLMFFADBD(value) {
        pb_1.Message.setField(this, 1758, value);
    }
    get entity_id() {
        return pb_1.Message.getFieldWithDefault(this, 1327, 0);
    }
    set entity_id(value) {
        pb_1.Message.setField(this, 1327, value);
    }
    get screen_x() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0);
    }
    set screen_x(value) {
        pb_1.Message.setField(this, 3, value);
    }
    get is_force_walk() {
        return pb_1.Message.getFieldWithDefault(this, 10, false);
    }
    set is_force_walk(value) {
        pb_1.Message.setField(this, 10, value);
    }
    get other_params() {
        return pb_1.Message.getFieldWithDefault(this, 1, []);
    }
    set other_params(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get follow_pos() {
        return pb_1.Message.getWrapperField(this, dependency_1.Vector, 8);
    }
    set follow_pos(value) {
        pb_1.Message.setWrapperField(this, 8, value);
    }
    get has_follow_pos() {
        return pb_1.Message.getField(this, 8) != null;
    }
    get is_allow_input() {
        return pb_1.Message.getFieldWithDefault(this, 2, false);
    }
    set is_allow_input(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get duration() {
        return pb_1.Message.getFieldWithDefault(this, 14, 0);
    }
    set duration(value) {
        pb_1.Message.setField(this, 14, value);
    }
    static fromObject(data) {
        const message = new BeginCameraSceneLookNotify({});
        if (data.Unk3000_MNLLCJMPMNH != null) {
            message.Unk3000_MNLLCJMPMNH = data.Unk3000_MNLLCJMPMNH;
        }
        if (data.Unk2700_DHAHEKOGHBJ != null) {
            message.Unk2700_DHAHEKOGHBJ = data.Unk2700_DHAHEKOGHBJ;
        }
        if (data.is_set_screen_xy != null) {
            message.is_set_screen_xy = data.is_set_screen_xy;
        }
        if (data.look_pos != null) {
            message.look_pos = dependency_1.Vector.fromObject(data.look_pos);
        }
        if (data.is_recover_keep_current != null) {
            message.is_recover_keep_current = data.is_recover_keep_current;
        }
        if (data.Unk3000_GOPIFPMFEPB != null) {
            message.Unk3000_GOPIFPMFEPB = data.Unk3000_GOPIFPMFEPB;
        }
        if (data.Unk2700_HIAKNNCKHJB != null) {
            message.Unk2700_HIAKNNCKHJB = data.Unk2700_HIAKNNCKHJB;
        }
        if (data.is_change_play_mode != null) {
            message.is_change_play_mode = data.is_change_play_mode;
        }
        if (data.Unk3000_IEFIKMHCKDH != null) {
            message.Unk3000_IEFIKMHCKDH = data.Unk3000_IEFIKMHCKDH;
        }
        if (data.screen_y != null) {
            message.screen_y = data.screen_y;
        }
        if (data.is_set_follow_pos != null) {
            message.is_set_follow_pos = data.is_set_follow_pos;
        }
        if (data.is_force != null) {
            message.is_force = data.is_force;
        }
        if (data.Unk3000_OGCLMFFADBD != null) {
            message.Unk3000_OGCLMFFADBD = data.Unk3000_OGCLMFFADBD;
        }
        if (data.entity_id != null) {
            message.entity_id = data.entity_id;
        }
        if (data.screen_x != null) {
            message.screen_x = data.screen_x;
        }
        if (data.is_force_walk != null) {
            message.is_force_walk = data.is_force_walk;
        }
        if (data.other_params != null) {
            message.other_params = data.other_params;
        }
        if (data.follow_pos != null) {
            message.follow_pos = dependency_1.Vector.fromObject(data.follow_pos);
        }
        if (data.is_allow_input != null) {
            message.is_allow_input = data.is_allow_input;
        }
        if (data.duration != null) {
            message.duration = data.duration;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.Unk3000_MNLLCJMPMNH != null) {
            data.Unk3000_MNLLCJMPMNH = this.Unk3000_MNLLCJMPMNH;
        }
        if (this.Unk2700_DHAHEKOGHBJ != null) {
            data.Unk2700_DHAHEKOGHBJ = this.Unk2700_DHAHEKOGHBJ;
        }
        if (this.is_set_screen_xy != null) {
            data.is_set_screen_xy = this.is_set_screen_xy;
        }
        if (this.look_pos != null) {
            data.look_pos = this.look_pos.toObject();
        }
        if (this.is_recover_keep_current != null) {
            data.is_recover_keep_current = this.is_recover_keep_current;
        }
        if (this.Unk3000_GOPIFPMFEPB != null) {
            data.Unk3000_GOPIFPMFEPB = this.Unk3000_GOPIFPMFEPB;
        }
        if (this.Unk2700_HIAKNNCKHJB != null) {
            data.Unk2700_HIAKNNCKHJB = this.Unk2700_HIAKNNCKHJB;
        }
        if (this.is_change_play_mode != null) {
            data.is_change_play_mode = this.is_change_play_mode;
        }
        if (this.Unk3000_IEFIKMHCKDH != null) {
            data.Unk3000_IEFIKMHCKDH = this.Unk3000_IEFIKMHCKDH;
        }
        if (this.screen_y != null) {
            data.screen_y = this.screen_y;
        }
        if (this.is_set_follow_pos != null) {
            data.is_set_follow_pos = this.is_set_follow_pos;
        }
        if (this.is_force != null) {
            data.is_force = this.is_force;
        }
        if (this.Unk3000_OGCLMFFADBD != null) {
            data.Unk3000_OGCLMFFADBD = this.Unk3000_OGCLMFFADBD;
        }
        if (this.entity_id != null) {
            data.entity_id = this.entity_id;
        }
        if (this.screen_x != null) {
            data.screen_x = this.screen_x;
        }
        if (this.is_force_walk != null) {
            data.is_force_walk = this.is_force_walk;
        }
        if (this.other_params != null) {
            data.other_params = this.other_params;
        }
        if (this.follow_pos != null) {
            data.follow_pos = this.follow_pos.toObject();
        }
        if (this.is_allow_input != null) {
            data.is_allow_input = this.is_allow_input;
        }
        if (this.duration != null) {
            data.duration = this.duration;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.Unk3000_MNLLCJMPMNH != 0)
            writer.writeUint32(1154, this.Unk3000_MNLLCJMPMNH);
        if (this.Unk2700_DHAHEKOGHBJ != 0)
            writer.writeFloat(7, this.Unk2700_DHAHEKOGHBJ);
        if (this.is_set_screen_xy != false)
            writer.writeBool(5, this.is_set_screen_xy);
        if (this.has_look_pos)
            writer.writeMessage(4, this.look_pos, () => this.look_pos.serialize(writer));
        if (this.is_recover_keep_current != false)
            writer.writeBool(11, this.is_recover_keep_current);
        if (this.Unk3000_GOPIFPMFEPB != false)
            writer.writeBool(1375, this.Unk3000_GOPIFPMFEPB);
        if (this.Unk2700_HIAKNNCKHJB != BeginCameraSceneLookNotify.Unk2700_LNCHDDOOECD.Unk2700_LNCHDDOOECD_Unk2700_ACOENBMDFBP)
            writer.writeEnum(6, this.Unk2700_HIAKNNCKHJB);
        if (this.is_change_play_mode != false)
            writer.writeBool(9, this.is_change_play_mode);
        if (this.Unk3000_IEFIKMHCKDH != 0)
            writer.writeUint32(1103, this.Unk3000_IEFIKMHCKDH);
        if (this.screen_y != 0)
            writer.writeFloat(15, this.screen_y);
        if (this.is_set_follow_pos != false)
            writer.writeBool(13, this.is_set_follow_pos);
        if (this.is_force != false)
            writer.writeBool(12, this.is_force);
        if (this.Unk3000_OGCLMFFADBD != 0)
            writer.writeFloat(1758, this.Unk3000_OGCLMFFADBD);
        if (this.entity_id != 0)
            writer.writeUint32(1327, this.entity_id);
        if (this.screen_x != 0)
            writer.writeFloat(3, this.screen_x);
        if (this.is_force_walk != false)
            writer.writeBool(10, this.is_force_walk);
        if (this.other_params.length)
            writer.writeRepeatedString(1, this.other_params);
        if (this.has_follow_pos)
            writer.writeMessage(8, this.follow_pos, () => this.follow_pos.serialize(writer));
        if (this.is_allow_input != false)
            writer.writeBool(2, this.is_allow_input);
        if (this.duration != 0)
            writer.writeFloat(14, this.duration);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BeginCameraSceneLookNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1154:
                    message.Unk3000_MNLLCJMPMNH = reader.readUint32();
                    break;
                case 7:
                    message.Unk2700_DHAHEKOGHBJ = reader.readFloat();
                    break;
                case 5:
                    message.is_set_screen_xy = reader.readBool();
                    break;
                case 4:
                    reader.readMessage(message.look_pos, () => message.look_pos = dependency_1.Vector.deserialize(reader));
                    break;
                case 11:
                    message.is_recover_keep_current = reader.readBool();
                    break;
                case 1375:
                    message.Unk3000_GOPIFPMFEPB = reader.readBool();
                    break;
                case 6:
                    message.Unk2700_HIAKNNCKHJB = reader.readEnum();
                    break;
                case 9:
                    message.is_change_play_mode = reader.readBool();
                    break;
                case 1103:
                    message.Unk3000_IEFIKMHCKDH = reader.readUint32();
                    break;
                case 15:
                    message.screen_y = reader.readFloat();
                    break;
                case 13:
                    message.is_set_follow_pos = reader.readBool();
                    break;
                case 12:
                    message.is_force = reader.readBool();
                    break;
                case 1758:
                    message.Unk3000_OGCLMFFADBD = reader.readFloat();
                    break;
                case 1327:
                    message.entity_id = reader.readUint32();
                    break;
                case 3:
                    message.screen_x = reader.readFloat();
                    break;
                case 10:
                    message.is_force_walk = reader.readBool();
                    break;
                case 1:
                    pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                    break;
                case 8:
                    reader.readMessage(message.follow_pos, () => message.follow_pos = dependency_1.Vector.deserialize(reader));
                    break;
                case 2:
                    message.is_allow_input = reader.readBool();
                    break;
                case 14:
                    message.duration = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return BeginCameraSceneLookNotify.deserialize(bytes);
    }
}
exports.BeginCameraSceneLookNotify = BeginCameraSceneLookNotify;
_BeginCameraSceneLookNotify_one_of_decls = new WeakMap();
(function (BeginCameraSceneLookNotify) {
    let Unk2700_LNCHDDOOECD;
    (function (Unk2700_LNCHDDOOECD) {
        Unk2700_LNCHDDOOECD[Unk2700_LNCHDDOOECD["Unk2700_LNCHDDOOECD_Unk2700_ACOENBMDFBP"] = 0] = "Unk2700_LNCHDDOOECD_Unk2700_ACOENBMDFBP";
        Unk2700_LNCHDDOOECD[Unk2700_LNCHDDOOECD["Unk2700_LNCHDDOOECD_Unk2700_FKBLCDFLCOM"] = 1] = "Unk2700_LNCHDDOOECD_Unk2700_FKBLCDFLCOM";
    })(Unk2700_LNCHDDOOECD = BeginCameraSceneLookNotify.Unk2700_LNCHDDOOECD || (BeginCameraSceneLookNotify.Unk2700_LNCHDDOOECD = {}));
})(BeginCameraSceneLookNotify = exports.BeginCameraSceneLookNotify || (exports.BeginCameraSceneLookNotify = {}));
