"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _BlessingGiveFriendPicRsp_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.BlessingGiveFriendPicRsp = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: BlessingGiveFriendPicRsp.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class BlessingGiveFriendPicRsp extends pb_1.Message {
    constructor(data) {
        super();
        _BlessingGiveFriendPicRsp_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _BlessingGiveFriendPicRsp_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("pic_id" in data && data.pic_id != undefined) {
                this.pic_id = data.pic_id;
            }
            if ("retcode" in data && data.retcode != undefined) {
                this.retcode = data.retcode;
            }
            if ("uid" in data && data.uid != undefined) {
                this.uid = data.uid;
            }
        }
    }
    get pic_id() {
        return pb_1.Message.getFieldWithDefault(this, 10, 0);
    }
    set pic_id(value) {
        pb_1.Message.setField(this, 10, value);
    }
    get retcode() {
        return pb_1.Message.getFieldWithDefault(this, 11, 0);
    }
    set retcode(value) {
        pb_1.Message.setField(this, 11, value);
    }
    get uid() {
        return pb_1.Message.getFieldWithDefault(this, 13, 0);
    }
    set uid(value) {
        pb_1.Message.setField(this, 13, value);
    }
    static fromObject(data) {
        const message = new BlessingGiveFriendPicRsp({});
        if (data.pic_id != null) {
            message.pic_id = data.pic_id;
        }
        if (data.retcode != null) {
            message.retcode = data.retcode;
        }
        if (data.uid != null) {
            message.uid = data.uid;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.pic_id != null) {
            data.pic_id = this.pic_id;
        }
        if (this.retcode != null) {
            data.retcode = this.retcode;
        }
        if (this.uid != null) {
            data.uid = this.uid;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.pic_id != 0)
            writer.writeUint32(10, this.pic_id);
        if (this.retcode != 0)
            writer.writeInt32(11, this.retcode);
        if (this.uid != 0)
            writer.writeUint32(13, this.uid);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BlessingGiveFriendPicRsp();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 10:
                    message.pic_id = reader.readUint32();
                    break;
                case 11:
                    message.retcode = reader.readInt32();
                    break;
                case 13:
                    message.uid = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return BlessingGiveFriendPicRsp.deserialize(bytes);
    }
}
exports.BlessingGiveFriendPicRsp = BlessingGiveFriendPicRsp;
_BlessingGiveFriendPicRsp_one_of_decls = new WeakMap();
