/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: BuoyantCombatSettleInfo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./BuoyantCombatGallerySettleInfo";
import * as pb_1 from "google-protobuf";
export class BuoyantCombatSettleInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        is_new_record?: boolean;
        settle_info?: dependency_1.BuoyantCombatGallerySettleInfo;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("is_new_record" in data && data.is_new_record != undefined) {
                this.is_new_record = data.is_new_record;
            }
            if ("settle_info" in data && data.settle_info != undefined) {
                this.settle_info = data.settle_info;
            }
        }
    }
    get is_new_record() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set is_new_record(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get settle_info() {
        return pb_1.Message.getWrapperField(this, dependency_1.BuoyantCombatGallerySettleInfo, 3) as dependency_1.BuoyantCombatGallerySettleInfo;
    }
    set settle_info(value: dependency_1.BuoyantCombatGallerySettleInfo) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get has_settle_info() {
        return pb_1.Message.getField(this, 3) != null;
    }
    static fromObject(data: {
        is_new_record?: boolean;
        settle_info?: ReturnType<typeof dependency_1.BuoyantCombatGallerySettleInfo.prototype.toObject>;
    }): BuoyantCombatSettleInfo {
        const message = new BuoyantCombatSettleInfo({});
        if (data.is_new_record != null) {
            message.is_new_record = data.is_new_record;
        }
        if (data.settle_info != null) {
            message.settle_info = dependency_1.BuoyantCombatGallerySettleInfo.fromObject(data.settle_info);
        }
        return message;
    }
    toObject() {
        const data: {
            is_new_record?: boolean;
            settle_info?: ReturnType<typeof dependency_1.BuoyantCombatGallerySettleInfo.prototype.toObject>;
        } = {};
        if (this.is_new_record != null) {
            data.is_new_record = this.is_new_record;
        }
        if (this.settle_info != null) {
            data.settle_info = this.settle_info.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.is_new_record != false)
            writer.writeBool(1, this.is_new_record);
        if (this.has_settle_info)
            writer.writeMessage(3, this.settle_info, () => this.settle_info.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BuoyantCombatSettleInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BuoyantCombatSettleInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.is_new_record = reader.readBool();
                    break;
                case 3:
                    reader.readMessage(message.settle_info, () => message.settle_info = dependency_1.BuoyantCombatGallerySettleInfo.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): BuoyantCombatSettleInfo {
        return BuoyantCombatSettleInfo.deserialize(bytes);
    }
}
