// @generated by protobuf-ts 2.8.2 with parameter output_typescript
// @generated from protobuf file "CardProductRewardNotify.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * enum CmdId {
 *   option allow_alias = true;
 *   NONE = 0;
 *   CMD_ID = 4135;
 *   ENET_CHANNEL_ID = 0;
 *   ENET_IS_RELIABLE = 1;
 * }
 *
 * @generated from protobuf message CardProductRewardNotify
 */
export interface CardProductRewardNotify {
    /**
     * @generated from protobuf field: uint32 hcoin = 6;
     */
    hcoin: number;
    /**
     * @generated from protobuf field: string product_id = 3;
     */
    productId: string;
    /**
     * @generated from protobuf field: uint32 remain_days = 4;
     */
    remainDays: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class CardProductRewardNotify$Type extends MessageType<CardProductRewardNotify> {
    constructor() {
        super("CardProductRewardNotify", [
            { no: 6, name: "hcoin", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "product_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "remain_days", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<CardProductRewardNotify>): CardProductRewardNotify {
        const message = { hcoin: 0, productId: "", remainDays: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CardProductRewardNotify>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CardProductRewardNotify): CardProductRewardNotify {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 hcoin */ 6:
                    message.hcoin = reader.uint32();
                    break;
                case /* string product_id */ 3:
                    message.productId = reader.string();
                    break;
                case /* uint32 remain_days */ 4:
                    message.remainDays = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CardProductRewardNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 hcoin = 6; */
        if (message.hcoin !== 0)
            writer.tag(6, WireType.Varint).uint32(message.hcoin);
        /* string product_id = 3; */
        if (message.productId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.productId);
        /* uint32 remain_days = 4; */
        if (message.remainDays !== 0)
            writer.tag(4, WireType.Varint).uint32(message.remainDays);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message CardProductRewardNotify
 */
export const CardProductRewardNotify = new CardProductRewardNotify$Type();
