/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: ChessSelectedCardsNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./ChessCardInfo";
import * as pb_1 from "google-protobuf";
export class ChessSelectedCardsNotify extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        selected_card_info_list?: dependency_1.ChessCardInfo[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [4], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("selected_card_info_list" in data && data.selected_card_info_list != undefined) {
                this.selected_card_info_list = data.selected_card_info_list;
            }
        }
    }
    get selected_card_info_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.ChessCardInfo, 4) as dependency_1.ChessCardInfo[];
    }
    set selected_card_info_list(value: dependency_1.ChessCardInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 4, value);
    }
    static fromObject(data: {
        selected_card_info_list?: ReturnType<typeof dependency_1.ChessCardInfo.prototype.toObject>[];
    }): ChessSelectedCardsNotify {
        const message = new ChessSelectedCardsNotify({});
        if (data.selected_card_info_list != null) {
            message.selected_card_info_list = data.selected_card_info_list.map(item => dependency_1.ChessCardInfo.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            selected_card_info_list?: ReturnType<typeof dependency_1.ChessCardInfo.prototype.toObject>[];
        } = {};
        if (this.selected_card_info_list != null) {
            data.selected_card_info_list = this.selected_card_info_list.map((item: dependency_1.ChessCardInfo) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.selected_card_info_list.length)
            writer.writeRepeatedMessage(4, this.selected_card_info_list, (item: dependency_1.ChessCardInfo) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChessSelectedCardsNotify {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChessSelectedCardsNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 4:
                    reader.readMessage(message.selected_card_info_list, () => pb_1.Message.addToRepeatedWrapperField(message, 4, dependency_1.ChessCardInfo.deserialize(reader), dependency_1.ChessCardInfo));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ChessSelectedCardsNotify {
        return ChessSelectedCardsNotify.deserialize(bytes);
    }
}
