"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _EntityTagChangeNotify_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.EntityTagChangeNotify = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: EntityTagChangeNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class EntityTagChangeNotify extends pb_1.Message {
    constructor(data) {
        super();
        _EntityTagChangeNotify_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _EntityTagChangeNotify_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("tag" in data && data.tag != undefined) {
                this.tag = data.tag;
            }
            if ("entity_id" in data && data.entity_id != undefined) {
                this.entity_id = data.entity_id;
            }
            if ("is_add" in data && data.is_add != undefined) {
                this.is_add = data.is_add;
            }
        }
    }
    get tag() {
        return pb_1.Message.getFieldWithDefault(this, 2, "");
    }
    set tag(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get entity_id() {
        return pb_1.Message.getFieldWithDefault(this, 8, 0);
    }
    set entity_id(value) {
        pb_1.Message.setField(this, 8, value);
    }
    get is_add() {
        return pb_1.Message.getFieldWithDefault(this, 10, false);
    }
    set is_add(value) {
        pb_1.Message.setField(this, 10, value);
    }
    static fromObject(data) {
        const message = new EntityTagChangeNotify({});
        if (data.tag != null) {
            message.tag = data.tag;
        }
        if (data.entity_id != null) {
            message.entity_id = data.entity_id;
        }
        if (data.is_add != null) {
            message.is_add = data.is_add;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.tag != null) {
            data.tag = this.tag;
        }
        if (this.entity_id != null) {
            data.entity_id = this.entity_id;
        }
        if (this.is_add != null) {
            data.is_add = this.is_add;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.tag.length)
            writer.writeString(2, this.tag);
        if (this.entity_id != 0)
            writer.writeUint32(8, this.entity_id);
        if (this.is_add != false)
            writer.writeBool(10, this.is_add);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new EntityTagChangeNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.tag = reader.readString();
                    break;
                case 8:
                    message.entity_id = reader.readUint32();
                    break;
                case 10:
                    message.is_add = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return EntityTagChangeNotify.deserialize(bytes);
    }
}
exports.EntityTagChangeNotify = EntityTagChangeNotify;
_EntityTagChangeNotify_one_of_decls = new WeakMap();
