"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _EntityFightPropNotify_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.EntityFightPropNotify = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: EntityFightPropNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class EntityFightPropNotify extends pb_1.Message {
    constructor(data) {
        super();
        _EntityFightPropNotify_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _EntityFightPropNotify_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("entity_id" in data && data.entity_id != undefined) {
                this.entity_id = data.entity_id;
            }
            if ("fight_prop_map" in data && data.fight_prop_map != undefined) {
                this.fight_prop_map = data.fight_prop_map;
            }
        }
        if (!this.fight_prop_map)
            this.fight_prop_map = new Map();
    }
    get entity_id() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0);
    }
    set entity_id(value) {
        pb_1.Message.setField(this, 4, value);
    }
    get fight_prop_map() {
        return pb_1.Message.getField(this, 8);
    }
    set fight_prop_map(value) {
        pb_1.Message.setField(this, 8, value);
    }
    static fromObject(data) {
        const message = new EntityFightPropNotify({});
        if (data.entity_id != null) {
            message.entity_id = data.entity_id;
        }
        if (typeof data.fight_prop_map == "object") {
            message.fight_prop_map = new Map(Object.entries(data.fight_prop_map).map(([key, value]) => [Number(key), value]));
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.entity_id != null) {
            data.entity_id = this.entity_id;
        }
        if (this.fight_prop_map.size > 0) {
            data.fight_prop_map = (Object.fromEntries)(this.fight_prop_map);
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.entity_id != 0)
            writer.writeUint32(4, this.entity_id);
        for (const [key, value] of this.fight_prop_map) {
            writer.writeMessage(8, this.fight_prop_map, () => {
                writer.writeUint32(1, key);
                writer.writeFloat(2, value);
            });
        }
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new EntityFightPropNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 4:
                    message.entity_id = reader.readUint32();
                    break;
                case 8:
                    reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.fight_prop_map, reader, reader.readUint32, reader.readFloat));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return EntityFightPropNotify.deserialize(bytes);
    }
}
exports.EntityFightPropNotify = EntityFightPropNotify;
_EntityFightPropNotify_one_of_decls = new WeakMap();
