"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _EquipRoguelikeRuneReq_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.EquipRoguelikeRuneReq = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: EquipRoguelikeRuneReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class EquipRoguelikeRuneReq extends pb_1.Message {
    constructor(data) {
        super();
        _EquipRoguelikeRuneReq_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], __classPrivateFieldGet(this, _EquipRoguelikeRuneReq_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("rune_list" in data && data.rune_list != undefined) {
                this.rune_list = data.rune_list;
            }
        }
    }
    get rune_list() {
        return pb_1.Message.getFieldWithDefault(this, 3, []);
    }
    set rune_list(value) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data) {
        const message = new EquipRoguelikeRuneReq({});
        if (data.rune_list != null) {
            message.rune_list = data.rune_list;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.rune_list != null) {
            data.rune_list = this.rune_list;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.rune_list.length)
            writer.writePackedUint32(3, this.rune_list);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new EquipRoguelikeRuneReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 3:
                    message.rune_list = reader.readPackedUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return EquipRoguelikeRuneReq.deserialize(bytes);
    }
}
exports.EquipRoguelikeRuneReq = EquipRoguelikeRuneReq;
_EquipRoguelikeRuneReq_one_of_decls = new WeakMap();
