/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: FishingScore.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class FishingScore extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        fishing_score_?: number;
        is_new_record?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("fishing_score_" in data && data.fishing_score_ != undefined) {
                this.fishing_score_ = data.fishing_score_;
            }
            if ("is_new_record" in data && data.is_new_record != undefined) {
                this.is_new_record = data.is_new_record;
            }
        }
    }
    get fishing_score_() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set fishing_score_(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get is_new_record() {
        return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
    }
    set is_new_record(value: boolean) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        fishing_score_?: number;
        is_new_record?: boolean;
    }): FishingScore {
        const message = new FishingScore({});
        if (data.fishing_score_ != null) {
            message.fishing_score_ = data.fishing_score_;
        }
        if (data.is_new_record != null) {
            message.is_new_record = data.is_new_record;
        }
        return message;
    }
    toObject() {
        const data: {
            fishing_score_?: number;
            is_new_record?: boolean;
        } = {};
        if (this.fishing_score_ != null) {
            data.fishing_score_ = this.fishing_score_;
        }
        if (this.is_new_record != null) {
            data.is_new_record = this.is_new_record;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.fishing_score_ != 0)
            writer.writeUint32(2, this.fishing_score_);
        if (this.is_new_record != false)
            writer.writeBool(4, this.is_new_record);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FishingScore {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FishingScore();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.fishing_score_ = reader.readUint32();
                    break;
                case 4:
                    message.is_new_record = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): FishingScore {
        return FishingScore.deserialize(bytes);
    }
}
