/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: GadgetAutoPickDropInfoNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Item";
import * as pb_1 from "google-protobuf";
export class GadgetAutoPickDropInfoNotify extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        item_list?: dependency_1.Item[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [11], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("item_list" in data && data.item_list != undefined) {
                this.item_list = data.item_list;
            }
        }
    }
    get item_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.Item, 11) as dependency_1.Item[];
    }
    set item_list(value: dependency_1.Item[]) {
        pb_1.Message.setRepeatedWrapperField(this, 11, value);
    }
    static fromObject(data: {
        item_list?: ReturnType<typeof dependency_1.Item.prototype.toObject>[];
    }): GadgetAutoPickDropInfoNotify {
        const message = new GadgetAutoPickDropInfoNotify({});
        if (data.item_list != null) {
            message.item_list = data.item_list.map(item => dependency_1.Item.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            item_list?: ReturnType<typeof dependency_1.Item.prototype.toObject>[];
        } = {};
        if (this.item_list != null) {
            data.item_list = this.item_list.map((item: dependency_1.Item) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.item_list.length)
            writer.writeRepeatedMessage(11, this.item_list, (item: dependency_1.Item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GadgetAutoPickDropInfoNotify {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GadgetAutoPickDropInfoNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 11:
                    reader.readMessage(message.item_list, () => pb_1.Message.addToRepeatedWrapperField(message, 11, dependency_1.Item.deserialize(reader), dependency_1.Item));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GadgetAutoPickDropInfoNotify {
        return GadgetAutoPickDropInfoNotify.deserialize(bytes);
    }
}
