// @generated by protobuf-ts 2.8.2 with parameter output_typescript
// @generated from protobuf file "GalleryStartSource.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
/**
 * @generated from protobuf enum GalleryStartSource
 */
export enum GalleryStartSource {
    /**
     * @generated from protobuf enum value: GALLERY_START_SOURCE_BY_NONE = 0;
     */
    BY_NONE = 0,
    /**
     * @generated from protobuf enum value: GALLERY_START_SOURCE_BY_MATCH = 1;
     */
    BY_MATCH = 1,
    /**
     * @generated from protobuf enum value: GALLERY_START_SOURCE_BY_DRAFT = 2;
     */
    BY_DRAFT = 2
}
