"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _GetAllH5ActivityInfoRsp_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetAllH5ActivityInfoRsp = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: GetAllH5ActivityInfoRsp.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const dependency_1 = require("./H5ActivityInfo");
const pb_1 = require("google-protobuf");
class GetAllH5ActivityInfoRsp extends pb_1.Message {
    constructor(data) {
        super();
        _GetAllH5ActivityInfoRsp_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [15], __classPrivateFieldGet(this, _GetAllH5ActivityInfoRsp_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("h5_activity_info_list" in data && data.h5_activity_info_list != undefined) {
                this.h5_activity_info_list = data.h5_activity_info_list;
            }
            if ("retcode" in data && data.retcode != undefined) {
                this.retcode = data.retcode;
            }
            if ("client_red_dot_timestamp" in data && data.client_red_dot_timestamp != undefined) {
                this.client_red_dot_timestamp = data.client_red_dot_timestamp;
            }
        }
    }
    get h5_activity_info_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.H5ActivityInfo, 15);
    }
    set h5_activity_info_list(value) {
        pb_1.Message.setRepeatedWrapperField(this, 15, value);
    }
    get retcode() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0);
    }
    set retcode(value) {
        pb_1.Message.setField(this, 5, value);
    }
    get client_red_dot_timestamp() {
        return pb_1.Message.getFieldWithDefault(this, 12, 0);
    }
    set client_red_dot_timestamp(value) {
        pb_1.Message.setField(this, 12, value);
    }
    static fromObject(data) {
        const message = new GetAllH5ActivityInfoRsp({});
        if (data.h5_activity_info_list != null) {
            message.h5_activity_info_list = data.h5_activity_info_list.map(item => dependency_1.H5ActivityInfo.fromObject(item));
        }
        if (data.retcode != null) {
            message.retcode = data.retcode;
        }
        if (data.client_red_dot_timestamp != null) {
            message.client_red_dot_timestamp = data.client_red_dot_timestamp;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.h5_activity_info_list != null) {
            data.h5_activity_info_list = this.h5_activity_info_list.map((item) => item.toObject());
        }
        if (this.retcode != null) {
            data.retcode = this.retcode;
        }
        if (this.client_red_dot_timestamp != null) {
            data.client_red_dot_timestamp = this.client_red_dot_timestamp;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.h5_activity_info_list.length)
            writer.writeRepeatedMessage(15, this.h5_activity_info_list, (item) => item.serialize(writer));
        if (this.retcode != 0)
            writer.writeInt32(5, this.retcode);
        if (this.client_red_dot_timestamp != 0)
            writer.writeUint32(12, this.client_red_dot_timestamp);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetAllH5ActivityInfoRsp();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 15:
                    reader.readMessage(message.h5_activity_info_list, () => pb_1.Message.addToRepeatedWrapperField(message, 15, dependency_1.H5ActivityInfo.deserialize(reader), dependency_1.H5ActivityInfo));
                    break;
                case 5:
                    message.retcode = reader.readInt32();
                    break;
                case 12:
                    message.client_red_dot_timestamp = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return GetAllH5ActivityInfoRsp.deserialize(bytes);
    }
}
exports.GetAllH5ActivityInfoRsp = GetAllH5ActivityInfoRsp;
_GetAllH5ActivityInfoRsp_one_of_decls = new WeakMap();
