// @generated by protobuf-ts 2.8.1 with parameter output_typescript
// @generated from protobuf file "GetScenePerformanceRsp.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Vector } from "./Vector";
/**
 * enum CmdId {
 *   option allow_alias = true;
 *   NONE = 0;
 *   CMD_ID = 3010;
 *   ENET_CHANNEL_ID = 0;
 *   ENET_IS_RELIABLE = 1;
 * }
 *
 * @generated from protobuf message GetScenePerformanceRsp
 */
export interface GetScenePerformanceRsp {
    /**
     * @generated from protobuf field: int32 retcode = 1;
     */
    retcode: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_GLNFIFPNJIE = 4 [json_name = "Unk3300GLNFIFPNJIE"];
     */
    unk3300GLNFIFPNJIE: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_IHBPCPCJIBC = 2 [json_name = "Unk3300IHBPCPCJIBC"];
     */
    unk3300IHBPCPCJIBC: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_MMALJIFDKJK = 13 [json_name = "Unk3300MMALJIFDKJK"];
     */
    unk3300MMALJIFDKJK: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_PDPJEMEKHKD = 10 [json_name = "Unk3300PDPJEMEKHKD"];
     */
    unk3300PDPJEMEKHKD: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_LIOFGAHKNIA = 14 [json_name = "Unk3300LIOFGAHKNIA"];
     */
    unk3300LIOFGAHKNIA: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_MIJMKLBGKML = 11 [json_name = "Unk3300MIJMKLBGKML"];
     */
    unk3300MIJMKLBGKML: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_JMLJLNKLJNP = 15 [json_name = "Unk3300JMLJLNKLJNP"];
     */
    unk3300JMLJLNKLJNP: number;
    /**
     * @generated from protobuf field: Vector pos = 9;
     */
    pos?: Vector;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetScenePerformanceRsp$Type extends MessageType<GetScenePerformanceRsp> {
    constructor() {
        super("GetScenePerformanceRsp", [
            { no: 1, name: "retcode", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "Unk3300_GLNFIFPNJIE", kind: "scalar", jsonName: "Unk3300GLNFIFPNJIE", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "Unk3300_IHBPCPCJIBC", kind: "scalar", jsonName: "Unk3300IHBPCPCJIBC", T: 13 /*ScalarType.UINT32*/ },
            { no: 13, name: "Unk3300_MMALJIFDKJK", kind: "scalar", jsonName: "Unk3300MMALJIFDKJK", T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "Unk3300_PDPJEMEKHKD", kind: "scalar", jsonName: "Unk3300PDPJEMEKHKD", T: 13 /*ScalarType.UINT32*/ },
            { no: 14, name: "Unk3300_LIOFGAHKNIA", kind: "scalar", jsonName: "Unk3300LIOFGAHKNIA", T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "Unk3300_MIJMKLBGKML", kind: "scalar", jsonName: "Unk3300MIJMKLBGKML", T: 13 /*ScalarType.UINT32*/ },
            { no: 15, name: "Unk3300_JMLJLNKLJNP", kind: "scalar", jsonName: "Unk3300JMLJLNKLJNP", T: 13 /*ScalarType.UINT32*/ },
            { no: 9, name: "pos", kind: "message", T: () => Vector }
        ]);
    }
    create(value?: PartialMessage<GetScenePerformanceRsp>): GetScenePerformanceRsp {
        const message = { retcode: 0, unk3300GLNFIFPNJIE: 0, unk3300IHBPCPCJIBC: 0, unk3300MMALJIFDKJK: 0, unk3300PDPJEMEKHKD: 0, unk3300LIOFGAHKNIA: 0, unk3300MIJMKLBGKML: 0, unk3300JMLJLNKLJNP: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetScenePerformanceRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetScenePerformanceRsp): GetScenePerformanceRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 retcode */ 1:
                    message.retcode = reader.int32();
                    break;
                case /* uint32 Unk3300_GLNFIFPNJIE = 4 [json_name = "Unk3300GLNFIFPNJIE"];*/ 4:
                    message.unk3300GLNFIFPNJIE = reader.uint32();
                    break;
                case /* uint32 Unk3300_IHBPCPCJIBC = 2 [json_name = "Unk3300IHBPCPCJIBC"];*/ 2:
                    message.unk3300IHBPCPCJIBC = reader.uint32();
                    break;
                case /* uint32 Unk3300_MMALJIFDKJK = 13 [json_name = "Unk3300MMALJIFDKJK"];*/ 13:
                    message.unk3300MMALJIFDKJK = reader.uint32();
                    break;
                case /* uint32 Unk3300_PDPJEMEKHKD = 10 [json_name = "Unk3300PDPJEMEKHKD"];*/ 10:
                    message.unk3300PDPJEMEKHKD = reader.uint32();
                    break;
                case /* uint32 Unk3300_LIOFGAHKNIA = 14 [json_name = "Unk3300LIOFGAHKNIA"];*/ 14:
                    message.unk3300LIOFGAHKNIA = reader.uint32();
                    break;
                case /* uint32 Unk3300_MIJMKLBGKML = 11 [json_name = "Unk3300MIJMKLBGKML"];*/ 11:
                    message.unk3300MIJMKLBGKML = reader.uint32();
                    break;
                case /* uint32 Unk3300_JMLJLNKLJNP = 15 [json_name = "Unk3300JMLJLNKLJNP"];*/ 15:
                    message.unk3300JMLJLNKLJNP = reader.uint32();
                    break;
                case /* Vector pos */ 9:
                    message.pos = Vector.internalBinaryRead(reader, reader.uint32(), options, message.pos);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetScenePerformanceRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 retcode = 1; */
        if (message.retcode !== 0)
            writer.tag(1, WireType.Varint).int32(message.retcode);
        /* uint32 Unk3300_GLNFIFPNJIE = 4 [json_name = "Unk3300GLNFIFPNJIE"]; */
        if (message.unk3300GLNFIFPNJIE !== 0)
            writer.tag(4, WireType.Varint).uint32(message.unk3300GLNFIFPNJIE);
        /* uint32 Unk3300_IHBPCPCJIBC = 2 [json_name = "Unk3300IHBPCPCJIBC"]; */
        if (message.unk3300IHBPCPCJIBC !== 0)
            writer.tag(2, WireType.Varint).uint32(message.unk3300IHBPCPCJIBC);
        /* uint32 Unk3300_MMALJIFDKJK = 13 [json_name = "Unk3300MMALJIFDKJK"]; */
        if (message.unk3300MMALJIFDKJK !== 0)
            writer.tag(13, WireType.Varint).uint32(message.unk3300MMALJIFDKJK);
        /* uint32 Unk3300_PDPJEMEKHKD = 10 [json_name = "Unk3300PDPJEMEKHKD"]; */
        if (message.unk3300PDPJEMEKHKD !== 0)
            writer.tag(10, WireType.Varint).uint32(message.unk3300PDPJEMEKHKD);
        /* uint32 Unk3300_LIOFGAHKNIA = 14 [json_name = "Unk3300LIOFGAHKNIA"]; */
        if (message.unk3300LIOFGAHKNIA !== 0)
            writer.tag(14, WireType.Varint).uint32(message.unk3300LIOFGAHKNIA);
        /* uint32 Unk3300_MIJMKLBGKML = 11 [json_name = "Unk3300MIJMKLBGKML"]; */
        if (message.unk3300MIJMKLBGKML !== 0)
            writer.tag(11, WireType.Varint).uint32(message.unk3300MIJMKLBGKML);
        /* uint32 Unk3300_JMLJLNKLJNP = 15 [json_name = "Unk3300JMLJLNKLJNP"]; */
        if (message.unk3300JMLJLNKLJNP !== 0)
            writer.tag(15, WireType.Varint).uint32(message.unk3300JMLJLNKLJNP);
        /* Vector pos = 9; */
        if (message.pos)
            Vector.internalBinaryWrite(message.pos, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GetScenePerformanceRsp
 */
export const GetScenePerformanceRsp = new GetScenePerformanceRsp$Type();
