/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: GMShowObstacleRsp.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./ObstacleInfo";
import * as pb_1 from "google-protobuf";
export class GMShowObstacleRsp extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        retcode?: number;
        obstacles?: dependency_1.ObstacleInfo[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [6], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("retcode" in data && data.retcode != undefined) {
                this.retcode = data.retcode;
            }
            if ("obstacles" in data && data.obstacles != undefined) {
                this.obstacles = data.obstacles;
            }
        }
    }
    get retcode() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set retcode(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    get obstacles() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.ObstacleInfo, 6) as dependency_1.ObstacleInfo[];
    }
    set obstacles(value: dependency_1.ObstacleInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 6, value);
    }
    static fromObject(data: {
        retcode?: number;
        obstacles?: ReturnType<typeof dependency_1.ObstacleInfo.prototype.toObject>[];
    }): GMShowObstacleRsp {
        const message = new GMShowObstacleRsp({});
        if (data.retcode != null) {
            message.retcode = data.retcode;
        }
        if (data.obstacles != null) {
            message.obstacles = data.obstacles.map(item => dependency_1.ObstacleInfo.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            retcode?: number;
            obstacles?: ReturnType<typeof dependency_1.ObstacleInfo.prototype.toObject>[];
        } = {};
        if (this.retcode != null) {
            data.retcode = this.retcode;
        }
        if (this.obstacles != null) {
            data.obstacles = this.obstacles.map((item: dependency_1.ObstacleInfo) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.retcode != 0)
            writer.writeInt32(5, this.retcode);
        if (this.obstacles.length)
            writer.writeRepeatedMessage(6, this.obstacles, (item: dependency_1.ObstacleInfo) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GMShowObstacleRsp {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GMShowObstacleRsp();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 5:
                    message.retcode = reader.readInt32();
                    break;
                case 6:
                    reader.readMessage(message.obstacles, () => pb_1.Message.addToRepeatedWrapperField(message, 6, dependency_1.ObstacleInfo.deserialize(reader), dependency_1.ObstacleInfo));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GMShowObstacleRsp {
        return GMShowObstacleRsp.deserialize(bytes);
    }
}
