/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: HideAndSeekPlayerBattleInfo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class HideAndSeekPlayerBattleInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        costume_id?: number;
        skill_list?: number[];
        is_ready?: boolean;
        avatar_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [15], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("costume_id" in data && data.costume_id != undefined) {
                this.costume_id = data.costume_id;
            }
            if ("skill_list" in data && data.skill_list != undefined) {
                this.skill_list = data.skill_list;
            }
            if ("is_ready" in data && data.is_ready != undefined) {
                this.is_ready = data.is_ready;
            }
            if ("avatar_id" in data && data.avatar_id != undefined) {
                this.avatar_id = data.avatar_id;
            }
        }
    }
    get costume_id() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set costume_id(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get skill_list() {
        return pb_1.Message.getFieldWithDefault(this, 15, []) as number[];
    }
    set skill_list(value: number[]) {
        pb_1.Message.setField(this, 15, value);
    }
    get is_ready() {
        return pb_1.Message.getFieldWithDefault(this, 12, false) as boolean;
    }
    set is_ready(value: boolean) {
        pb_1.Message.setField(this, 12, value);
    }
    get avatar_id() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set avatar_id(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
        costume_id?: number;
        skill_list?: number[];
        is_ready?: boolean;
        avatar_id?: number;
    }): HideAndSeekPlayerBattleInfo {
        const message = new HideAndSeekPlayerBattleInfo({});
        if (data.costume_id != null) {
            message.costume_id = data.costume_id;
        }
        if (data.skill_list != null) {
            message.skill_list = data.skill_list;
        }
        if (data.is_ready != null) {
            message.is_ready = data.is_ready;
        }
        if (data.avatar_id != null) {
            message.avatar_id = data.avatar_id;
        }
        return message;
    }
    toObject() {
        const data: {
            costume_id?: number;
            skill_list?: number[];
            is_ready?: boolean;
            avatar_id?: number;
        } = {};
        if (this.costume_id != null) {
            data.costume_id = this.costume_id;
        }
        if (this.skill_list != null) {
            data.skill_list = this.skill_list;
        }
        if (this.is_ready != null) {
            data.is_ready = this.is_ready;
        }
        if (this.avatar_id != null) {
            data.avatar_id = this.avatar_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.costume_id != 0)
            writer.writeUint32(3, this.costume_id);
        if (this.skill_list.length)
            writer.writePackedUint32(15, this.skill_list);
        if (this.is_ready != false)
            writer.writeBool(12, this.is_ready);
        if (this.avatar_id != 0)
            writer.writeUint32(6, this.avatar_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): HideAndSeekPlayerBattleInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new HideAndSeekPlayerBattleInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 3:
                    message.costume_id = reader.readUint32();
                    break;
                case 15:
                    message.skill_list = reader.readPackedUint32();
                    break;
                case 12:
                    message.is_ready = reader.readBool();
                    break;
                case 6:
                    message.avatar_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): HideAndSeekPlayerBattleInfo {
        return HideAndSeekPlayerBattleInfo.deserialize(bytes);
    }
}
