/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: HideAndSeekStageType.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum HideAndSeekStageType {
    HIDE_AND_SEEK_STAGE_TYPE_PREPARE = 0,
    HIDE_AND_SEEK_STAGE_TYPE_PICK = 1,
    HIDE_AND_SEEK_STAGE_TYPE_GAME = 2,
    HIDE_AND_SEEK_STAGE_TYPE_HIDE = 3,
    HIDE_AND_SEEK_STAGE_TYPE_SEEK = 4,
    HIDE_AND_SEEK_STAGE_TYPE_SETTLE = 5
}
