// @generated by protobuf-ts 2.8.2 with parameter output_typescript
// @generated from protobuf file "HideAndSeekSettleNotify.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { HideAndSeekSettleInfo } from "./HideAndSeekSettleInfo";
import { ExhibitionDisplayInfo } from "./ExhibitionDisplayInfo";
/**
 * enum CmdId {
 *   option allow_alias = true;
 *   NONE = 0;
 *   CMD_ID = 5391;
 *   ENET_CHANNEL_ID = 0;
 *   ENET_IS_RELIABLE = 1;
 * }
 *
 * @generated from protobuf message HideAndSeekSettleNotify
 */
export interface HideAndSeekSettleNotify {
    /**
     * @generated from protobuf field: uint32 play_index = 6;
     */
    playIndex: number;
    /**
     * @generated from protobuf field: repeated ExhibitionDisplayInfo score_list = 11;
     */
    scoreList: ExhibitionDisplayInfo[];
    /**
     * @generated from protobuf field: HideAndSeekSettleNotify.SettleReason reason = 1;
     */
    reason: HideAndSeekSettleNotify_SettleReason;
    /**
     * @generated from protobuf field: repeated uint32 winner_list = 2;
     */
    winnerList: number[];
    /**
     * @generated from protobuf field: uint32 cost_time = 15;
     */
    costTime: number;
    /**
     * @generated from protobuf field: uint32 stage_type = 7;
     */
    stageType: number;
    /**
     * @generated from protobuf field: bool is_record_score = 5;
     */
    isRecordScore: boolean;
    /**
     * @generated from protobuf field: repeated HideAndSeekSettleInfo settle_info_list = 4;
     */
    settleInfoList: HideAndSeekSettleInfo[];
}
/**
 * @generated from protobuf enum HideAndSeekSettleNotify.SettleReason
 */
export enum HideAndSeekSettleNotify_SettleReason {
    /**
     * @generated from protobuf enum value: SETTLE_REASON_TIME_OUT = 0;
     */
    TIME_OUT = 0,
    /**
     * @generated from protobuf enum value: SETTLE_REASON_PLAY_END = 1;
     */
    PLAY_END = 1,
    /**
     * @generated from protobuf enum value: SETTLE_REASON_PLAYER_QUIT = 2;
     */
    PLAYER_QUIT = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class HideAndSeekSettleNotify$Type extends MessageType<HideAndSeekSettleNotify> {
    constructor() {
        super("HideAndSeekSettleNotify", [
            { no: 6, name: "play_index", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "score_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ExhibitionDisplayInfo },
            { no: 1, name: "reason", kind: "enum", T: () => ["HideAndSeekSettleNotify.SettleReason", HideAndSeekSettleNotify_SettleReason, "SETTLE_REASON_"] },
            { no: 2, name: "winner_list", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 15, name: "cost_time", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "stage_type", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "is_record_score", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "settle_info_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => HideAndSeekSettleInfo }
        ]);
    }
    create(value?: PartialMessage<HideAndSeekSettleNotify>): HideAndSeekSettleNotify {
        const message = { playIndex: 0, scoreList: [], reason: 0, winnerList: [], costTime: 0, stageType: 0, isRecordScore: false, settleInfoList: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HideAndSeekSettleNotify>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HideAndSeekSettleNotify): HideAndSeekSettleNotify {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 play_index */ 6:
                    message.playIndex = reader.uint32();
                    break;
                case /* repeated ExhibitionDisplayInfo score_list */ 11:
                    message.scoreList.push(ExhibitionDisplayInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* HideAndSeekSettleNotify.SettleReason reason */ 1:
                    message.reason = reader.int32();
                    break;
                case /* repeated uint32 winner_list */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.winnerList.push(reader.uint32());
                    else
                        message.winnerList.push(reader.uint32());
                    break;
                case /* uint32 cost_time */ 15:
                    message.costTime = reader.uint32();
                    break;
                case /* uint32 stage_type */ 7:
                    message.stageType = reader.uint32();
                    break;
                case /* bool is_record_score */ 5:
                    message.isRecordScore = reader.bool();
                    break;
                case /* repeated HideAndSeekSettleInfo settle_info_list */ 4:
                    message.settleInfoList.push(HideAndSeekSettleInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HideAndSeekSettleNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 play_index = 6; */
        if (message.playIndex !== 0)
            writer.tag(6, WireType.Varint).uint32(message.playIndex);
        /* repeated ExhibitionDisplayInfo score_list = 11; */
        for (let i = 0; i < message.scoreList.length; i++)
            ExhibitionDisplayInfo.internalBinaryWrite(message.scoreList[i], writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* HideAndSeekSettleNotify.SettleReason reason = 1; */
        if (message.reason !== 0)
            writer.tag(1, WireType.Varint).int32(message.reason);
        /* repeated uint32 winner_list = 2; */
        if (message.winnerList.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.winnerList.length; i++)
                writer.uint32(message.winnerList[i]);
            writer.join();
        }
        /* uint32 cost_time = 15; */
        if (message.costTime !== 0)
            writer.tag(15, WireType.Varint).uint32(message.costTime);
        /* uint32 stage_type = 7; */
        if (message.stageType !== 0)
            writer.tag(7, WireType.Varint).uint32(message.stageType);
        /* bool is_record_score = 5; */
        if (message.isRecordScore !== false)
            writer.tag(5, WireType.Varint).bool(message.isRecordScore);
        /* repeated HideAndSeekSettleInfo settle_info_list = 4; */
        for (let i = 0; i < message.settleInfoList.length; i++)
            HideAndSeekSettleInfo.internalBinaryWrite(message.settleInfoList[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message HideAndSeekSettleNotify
 */
export const HideAndSeekSettleNotify = new HideAndSeekSettleNotify$Type();
