// @generated by protobuf-ts 2.8.1 with parameter generate_dependencies,output_typescript
// @generated from protobuf file "HomeBlueprintBatchBriefMuipData.proto" (package "com.midnights.game", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { HomeBlueprintBriefMuipData } from "./HomeBlueprintBriefMuipData";
/**
 * @generated from protobuf message com.midnights.game.HomeBlueprintBatchBriefMuipData
 */
export interface HomeBlueprintBatchBriefMuipData {
    /**
     * @generated from protobuf field: repeated com.midnights.game.HomeBlueprintBriefMuipData brief_list = 1;
     */
    briefList: HomeBlueprintBriefMuipData[];
    /**
     * @generated from protobuf field: repeated string not_exist_share_code_list = 2;
     */
    notExistShareCodeList: string[];
}
// @generated message type with reflection information, may provide speed optimized methods
class HomeBlueprintBatchBriefMuipData$Type extends MessageType<HomeBlueprintBatchBriefMuipData> {
    constructor() {
        super("com.midnights.game.HomeBlueprintBatchBriefMuipData", [
            { no: 1, name: "brief_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => HomeBlueprintBriefMuipData },
            { no: 2, name: "not_exist_share_code_list", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HomeBlueprintBatchBriefMuipData>): HomeBlueprintBatchBriefMuipData {
        const message = { briefList: [], notExistShareCodeList: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HomeBlueprintBatchBriefMuipData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HomeBlueprintBatchBriefMuipData): HomeBlueprintBatchBriefMuipData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated com.midnights.game.HomeBlueprintBriefMuipData brief_list */ 1:
                    message.briefList.push(HomeBlueprintBriefMuipData.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated string not_exist_share_code_list */ 2:
                    message.notExistShareCodeList.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HomeBlueprintBatchBriefMuipData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated com.midnights.game.HomeBlueprintBriefMuipData brief_list = 1; */
        for (let i = 0; i < message.briefList.length; i++)
            HomeBlueprintBriefMuipData.internalBinaryWrite(message.briefList[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated string not_exist_share_code_list = 2; */
        for (let i = 0; i < message.notExistShareCodeList.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.notExistShareCodeList[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.midnights.game.HomeBlueprintBatchBriefMuipData
 */
export const HomeBlueprintBatchBriefMuipData = new HomeBlueprintBatchBriefMuipData$Type();
