// @generated by protobuf-ts 2.8.1 with parameter generate_dependencies,output_typescript
// @generated from protobuf file "HomeSceneArrangementMuipData.proto" (package "com.midnights.game", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { HomeBlockArrangementMuipData } from "./HomeBlockArrangementMuipData";
/**
 * @generated from protobuf message com.midnights.game.HomeSceneArrangementMuipData
 */
export interface HomeSceneArrangementMuipData {
    /**
     * @generated from protobuf field: optional uint32 module_id = 1;
     */
    moduleId?: number;
    /**
     * @generated from protobuf field: optional uint32 scene_id = 2;
     */
    sceneId?: number;
    /**
     * @generated from protobuf field: optional bool is_room = 3;
     */
    isRoom?: boolean;
    /**
     * @generated from protobuf field: repeated com.midnights.game.HomeBlockArrangementMuipData block_data_list = 4;
     */
    blockDataList: HomeBlockArrangementMuipData[];
}
// @generated message type with reflection information, may provide speed optimized methods
class HomeSceneArrangementMuipData$Type extends MessageType<HomeSceneArrangementMuipData> {
    constructor() {
        super("com.midnights.game.HomeSceneArrangementMuipData", [
            { no: 1, name: "module_id", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "scene_id", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "is_room", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "block_data_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => HomeBlockArrangementMuipData }
        ]);
    }
    create(value?: PartialMessage<HomeSceneArrangementMuipData>): HomeSceneArrangementMuipData {
        const message = { blockDataList: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HomeSceneArrangementMuipData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HomeSceneArrangementMuipData): HomeSceneArrangementMuipData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional uint32 module_id */ 1:
                    message.moduleId = reader.uint32();
                    break;
                case /* optional uint32 scene_id */ 2:
                    message.sceneId = reader.uint32();
                    break;
                case /* optional bool is_room */ 3:
                    message.isRoom = reader.bool();
                    break;
                case /* repeated com.midnights.game.HomeBlockArrangementMuipData block_data_list */ 4:
                    message.blockDataList.push(HomeBlockArrangementMuipData.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HomeSceneArrangementMuipData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional uint32 module_id = 1; */
        if (message.moduleId !== undefined)
            writer.tag(1, WireType.Varint).uint32(message.moduleId);
        /* optional uint32 scene_id = 2; */
        if (message.sceneId !== undefined)
            writer.tag(2, WireType.Varint).uint32(message.sceneId);
        /* optional bool is_room = 3; */
        if (message.isRoom !== undefined)
            writer.tag(3, WireType.Varint).bool(message.isRoom);
        /* repeated com.midnights.game.HomeBlockArrangementMuipData block_data_list = 4; */
        for (let i = 0; i < message.blockDataList.length; i++)
            HomeBlockArrangementMuipData.internalBinaryWrite(message.blockDataList[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.midnights.game.HomeSceneArrangementMuipData
 */
export const HomeSceneArrangementMuipData = new HomeSceneArrangementMuipData$Type();
