"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _HomeLimitedShopInfoRsp_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.HomeLimitedShopInfoRsp = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: HomeLimitedShopInfoRsp.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const dependency_1 = require("./HomeLimitedShopInfo");
const pb_1 = require("google-protobuf");
class HomeLimitedShopInfoRsp extends pb_1.Message {
    constructor(data) {
        super();
        _HomeLimitedShopInfoRsp_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _HomeLimitedShopInfoRsp_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("shop_info" in data && data.shop_info != undefined) {
                this.shop_info = data.shop_info;
            }
            if ("retcode" in data && data.retcode != undefined) {
                this.retcode = data.retcode;
            }
        }
    }
    get shop_info() {
        return pb_1.Message.getWrapperField(this, dependency_1.HomeLimitedShopInfo, 10);
    }
    set shop_info(value) {
        pb_1.Message.setWrapperField(this, 10, value);
    }
    get has_shop_info() {
        return pb_1.Message.getField(this, 10) != null;
    }
    get retcode() {
        return pb_1.Message.getFieldWithDefault(this, 7, 0);
    }
    set retcode(value) {
        pb_1.Message.setField(this, 7, value);
    }
    static fromObject(data) {
        const message = new HomeLimitedShopInfoRsp({});
        if (data.shop_info != null) {
            message.shop_info = dependency_1.HomeLimitedShopInfo.fromObject(data.shop_info);
        }
        if (data.retcode != null) {
            message.retcode = data.retcode;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.shop_info != null) {
            data.shop_info = this.shop_info.toObject();
        }
        if (this.retcode != null) {
            data.retcode = this.retcode;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_shop_info)
            writer.writeMessage(10, this.shop_info, () => this.shop_info.serialize(writer));
        if (this.retcode != 0)
            writer.writeInt32(7, this.retcode);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new HomeLimitedShopInfoRsp();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 10:
                    reader.readMessage(message.shop_info, () => message.shop_info = dependency_1.HomeLimitedShopInfo.deserialize(reader));
                    break;
                case 7:
                    message.retcode = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return HomeLimitedShopInfoRsp.deserialize(bytes);
    }
}
exports.HomeLimitedShopInfoRsp = HomeLimitedShopInfoRsp;
_HomeLimitedShopInfoRsp_one_of_decls = new WeakMap();
