"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _HomeCustomFurnitureInfoNotify_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.HomeCustomFurnitureInfoNotify = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: HomeCustomFurnitureInfoNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const dependency_1 = require("./HomeCustomFurnitureInfo");
const pb_1 = require("google-protobuf");
class HomeCustomFurnitureInfoNotify extends pb_1.Message {
    constructor(data) {
        super();
        _HomeCustomFurnitureInfoNotify_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [4, 11], __classPrivateFieldGet(this, _HomeCustomFurnitureInfoNotify_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("delete_custom_furniture_list" in data && data.delete_custom_furniture_list != undefined) {
                this.delete_custom_furniture_list = data.delete_custom_furniture_list;
            }
            if ("used_sub_furniture_count_map" in data && data.used_sub_furniture_count_map != undefined) {
                this.used_sub_furniture_count_map = data.used_sub_furniture_count_map;
            }
            if ("custom_furniture_info_list" in data && data.custom_furniture_info_list != undefined) {
                this.custom_furniture_info_list = data.custom_furniture_info_list;
            }
        }
        if (!this.used_sub_furniture_count_map)
            this.used_sub_furniture_count_map = new Map();
    }
    get delete_custom_furniture_list() {
        return pb_1.Message.getFieldWithDefault(this, 4, []);
    }
    set delete_custom_furniture_list(value) {
        pb_1.Message.setField(this, 4, value);
    }
    get used_sub_furniture_count_map() {
        return pb_1.Message.getField(this, 15);
    }
    set used_sub_furniture_count_map(value) {
        pb_1.Message.setField(this, 15, value);
    }
    get custom_furniture_info_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.HomeCustomFurnitureInfo, 11);
    }
    set custom_furniture_info_list(value) {
        pb_1.Message.setRepeatedWrapperField(this, 11, value);
    }
    static fromObject(data) {
        const message = new HomeCustomFurnitureInfoNotify({});
        if (data.delete_custom_furniture_list != null) {
            message.delete_custom_furniture_list = data.delete_custom_furniture_list;
        }
        if (typeof data.used_sub_furniture_count_map == "object") {
            message.used_sub_furniture_count_map = new Map(Object.entries(data.used_sub_furniture_count_map).map(([key, value]) => [Number(key), value]));
        }
        if (data.custom_furniture_info_list != null) {
            message.custom_furniture_info_list = data.custom_furniture_info_list.map(item => dependency_1.HomeCustomFurnitureInfo.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.delete_custom_furniture_list != null) {
            data.delete_custom_furniture_list = this.delete_custom_furniture_list;
        }
        if (this.used_sub_furniture_count_map.size > 0) {
            data.used_sub_furniture_count_map = (Object.fromEntries)(this.used_sub_furniture_count_map);
        }
        if (this.custom_furniture_info_list != null) {
            data.custom_furniture_info_list = this.custom_furniture_info_list.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.delete_custom_furniture_list.length)
            writer.writePackedUint32(4, this.delete_custom_furniture_list);
        for (const [key, value] of this.used_sub_furniture_count_map) {
            writer.writeMessage(15, this.used_sub_furniture_count_map, () => {
                writer.writeUint32(1, key);
                writer.writeUint32(2, value);
            });
        }
        if (this.custom_furniture_info_list.length)
            writer.writeRepeatedMessage(11, this.custom_furniture_info_list, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new HomeCustomFurnitureInfoNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 4:
                    message.delete_custom_furniture_list = reader.readPackedUint32();
                    break;
                case 15:
                    reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.used_sub_furniture_count_map, reader, reader.readUint32, reader.readUint32));
                    break;
                case 11:
                    reader.readMessage(message.custom_furniture_info_list, () => pb_1.Message.addToRepeatedWrapperField(message, 11, dependency_1.HomeCustomFurnitureInfo.deserialize(reader), dependency_1.HomeCustomFurnitureInfo));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return HomeCustomFurnitureInfoNotify.deserialize(bytes);
    }
}
exports.HomeCustomFurnitureInfoNotify = HomeCustomFurnitureInfoNotify;
_HomeCustomFurnitureInfoNotify_one_of_decls = new WeakMap();
