/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: HostPlayerNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class HostPlayerNotify extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        host_peer_id?: number;
        host_uid?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("host_peer_id" in data && data.host_peer_id != undefined) {
                this.host_peer_id = data.host_peer_id;
            }
            if ("host_uid" in data && data.host_uid != undefined) {
                this.host_uid = data.host_uid;
            }
        }
    }
    get host_peer_id() {
        return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
    }
    set host_peer_id(value: number) {
        pb_1.Message.setField(this, 13, value);
    }
    get host_uid() {
        return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
    }
    set host_uid(value: number) {
        pb_1.Message.setField(this, 10, value);
    }
    static fromObject(data: {
        host_peer_id?: number;
        host_uid?: number;
    }): HostPlayerNotify {
        const message = new HostPlayerNotify({});
        if (data.host_peer_id != null) {
            message.host_peer_id = data.host_peer_id;
        }
        if (data.host_uid != null) {
            message.host_uid = data.host_uid;
        }
        return message;
    }
    toObject() {
        const data: {
            host_peer_id?: number;
            host_uid?: number;
        } = {};
        if (this.host_peer_id != null) {
            data.host_peer_id = this.host_peer_id;
        }
        if (this.host_uid != null) {
            data.host_uid = this.host_uid;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.host_peer_id != 0)
            writer.writeUint32(13, this.host_peer_id);
        if (this.host_uid != 0)
            writer.writeUint32(10, this.host_uid);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): HostPlayerNotify {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new HostPlayerNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 13:
                    message.host_peer_id = reader.readUint32();
                    break;
                case 10:
                    message.host_uid = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): HostPlayerNotify {
        return HostPlayerNotify.deserialize(bytes);
    }
}
