// @generated by protobuf-ts 2.8.1 with parameter output_typescript
// @generated from protobuf file "InBattleMechanicusSettleNotify.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { MultistageSettleWatcherInfo } from "./MultistageSettleWatcherInfo";
/**
 * enum CmdId {
 *   option allow_alias = true;
 *   NONE = 0;
 *   CMD_ID = 5342;
 *   ENET_CHANNEL_ID = 0;
 *   ENET_IS_RELIABLE = 1;
 * }
 *
 * @generated from protobuf message InBattleMechanicusSettleNotify
 */
export interface InBattleMechanicusSettleNotify {
    /**
     * @generated from protobuf field: uint64 scene_time_ms = 15;
     */
    sceneTimeMs: bigint;
    /**
     * @generated from protobuf field: uint32 group_id = 5;
     */
    groupId: number;
    /**
     * @generated from protobuf field: repeated MultistageSettleWatcherInfo watcher_list = 2;
     */
    watcherList: MultistageSettleWatcherInfo[];
    /**
     * @generated from protobuf field: uint32 Unk3300_NAMBBHMJJLN = 13 [json_name = "Unk3300NAMBBHMJJLN"];
     */
    unk3300NAMBBHMJJLN: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_HAEOPAOBBFE = 3 [json_name = "Unk3300HAEOPAOBBFE"];
     */
    unk3300HAEOPAOBBFE: number;
    /**
     * @generated from protobuf field: uint32 Unk3300_EKAIAPLNIPM = 10 [json_name = "Unk3300EKAIAPLNIPM"];
     */
    unk3300EKAIAPLNIPM: number;
    /**
     * @generated from protobuf field: uint32 play_index = 6;
     */
    playIndex: number;
    /**
     * @generated from protobuf field: bool is_success = 1;
     */
    isSuccess: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class InBattleMechanicusSettleNotify$Type extends MessageType<InBattleMechanicusSettleNotify> {
    constructor() {
        super("InBattleMechanicusSettleNotify", [
            { no: 15, name: "scene_time_ms", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "group_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "watcher_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MultistageSettleWatcherInfo },
            { no: 13, name: "Unk3300_NAMBBHMJJLN", kind: "scalar", jsonName: "Unk3300NAMBBHMJJLN", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "Unk3300_HAEOPAOBBFE", kind: "scalar", jsonName: "Unk3300HAEOPAOBBFE", T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "Unk3300_EKAIAPLNIPM", kind: "scalar", jsonName: "Unk3300EKAIAPLNIPM", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "play_index", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 1, name: "is_success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<InBattleMechanicusSettleNotify>): InBattleMechanicusSettleNotify {
        const message = { sceneTimeMs: 0n, groupId: 0, watcherList: [], unk3300NAMBBHMJJLN: 0, unk3300HAEOPAOBBFE: 0, unk3300EKAIAPLNIPM: 0, playIndex: 0, isSuccess: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<InBattleMechanicusSettleNotify>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InBattleMechanicusSettleNotify): InBattleMechanicusSettleNotify {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 scene_time_ms */ 15:
                    message.sceneTimeMs = reader.uint64().toBigInt();
                    break;
                case /* uint32 group_id */ 5:
                    message.groupId = reader.uint32();
                    break;
                case /* repeated MultistageSettleWatcherInfo watcher_list */ 2:
                    message.watcherList.push(MultistageSettleWatcherInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* uint32 Unk3300_NAMBBHMJJLN = 13 [json_name = "Unk3300NAMBBHMJJLN"];*/ 13:
                    message.unk3300NAMBBHMJJLN = reader.uint32();
                    break;
                case /* uint32 Unk3300_HAEOPAOBBFE = 3 [json_name = "Unk3300HAEOPAOBBFE"];*/ 3:
                    message.unk3300HAEOPAOBBFE = reader.uint32();
                    break;
                case /* uint32 Unk3300_EKAIAPLNIPM = 10 [json_name = "Unk3300EKAIAPLNIPM"];*/ 10:
                    message.unk3300EKAIAPLNIPM = reader.uint32();
                    break;
                case /* uint32 play_index */ 6:
                    message.playIndex = reader.uint32();
                    break;
                case /* bool is_success */ 1:
                    message.isSuccess = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InBattleMechanicusSettleNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 scene_time_ms = 15; */
        if (message.sceneTimeMs !== 0n)
            writer.tag(15, WireType.Varint).uint64(message.sceneTimeMs);
        /* uint32 group_id = 5; */
        if (message.groupId !== 0)
            writer.tag(5, WireType.Varint).uint32(message.groupId);
        /* repeated MultistageSettleWatcherInfo watcher_list = 2; */
        for (let i = 0; i < message.watcherList.length; i++)
            MultistageSettleWatcherInfo.internalBinaryWrite(message.watcherList[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* uint32 Unk3300_NAMBBHMJJLN = 13 [json_name = "Unk3300NAMBBHMJJLN"]; */
        if (message.unk3300NAMBBHMJJLN !== 0)
            writer.tag(13, WireType.Varint).uint32(message.unk3300NAMBBHMJJLN);
        /* uint32 Unk3300_HAEOPAOBBFE = 3 [json_name = "Unk3300HAEOPAOBBFE"]; */
        if (message.unk3300HAEOPAOBBFE !== 0)
            writer.tag(3, WireType.Varint).uint32(message.unk3300HAEOPAOBBFE);
        /* uint32 Unk3300_EKAIAPLNIPM = 10 [json_name = "Unk3300EKAIAPLNIPM"]; */
        if (message.unk3300EKAIAPLNIPM !== 0)
            writer.tag(10, WireType.Varint).uint32(message.unk3300EKAIAPLNIPM);
        /* uint32 play_index = 6; */
        if (message.playIndex !== 0)
            writer.tag(6, WireType.Varint).uint32(message.playIndex);
        /* bool is_success = 1; */
        if (message.isSuccess !== false)
            writer.tag(1, WireType.Varint).bool(message.isSuccess);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InBattleMechanicusSettleNotify
 */
export const InBattleMechanicusSettleNotify = new InBattleMechanicusSettleNotify$Type();
