"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InteractType = void 0;
var InteractType;
(function (InteractType) {
    InteractType[InteractType["INTERACT_TYPE_NONE"] = 0] = "INTERACT_TYPE_NONE";
    InteractType[InteractType["INTERACT_TYPE_PICK_ITEM"] = 1] = "INTERACT_TYPE_PICK_ITEM";
    InteractType[InteractType["INTERACT_TYPE_GATHER"] = 2] = "INTERACT_TYPE_GATHER";
    InteractType[InteractType["INTERACT_TYPE_OPEN_CHEST"] = 3] = "INTERACT_TYPE_OPEN_CHEST";
    InteractType[InteractType["INTERACT_TYPE_OPEN_STATUE"] = 4] = "INTERACT_TYPE_OPEN_STATUE";
    InteractType[InteractType["INTERACT_TYPE_CONSUM"] = 5] = "INTERACT_TYPE_CONSUM";
    InteractType[InteractType["INTERACT_TYPE_MP_PLAY_REWARD"] = 6] = "INTERACT_TYPE_MP_PLAY_REWARD";
    InteractType[InteractType["INTERACT_TYPE_VIEW"] = 7] = "INTERACT_TYPE_VIEW";
    InteractType[InteractType["INTERACT_TYPE_GENERAL_REWARD"] = 8] = "INTERACT_TYPE_GENERAL_REWARD";
    InteractType[InteractType["INTERACT_TYPE_MIRACLE_RING"] = 9] = "INTERACT_TYPE_MIRACLE_RING";
    InteractType[InteractType["INTERACT_TYPE_FOUNDATION"] = 10] = "INTERACT_TYPE_FOUNDATION";
    InteractType[InteractType["INTERACT_TYPE_ECHO_SHELL"] = 11] = "INTERACT_TYPE_ECHO_SHELL";
    InteractType[InteractType["INTERACT_TYPE_HOME_GATHER"] = 12] = "INTERACT_TYPE_HOME_GATHER";
    InteractType[InteractType["INTERACT_TYPE_ENV_ANIMAL"] = 13] = "INTERACT_TYPE_ENV_ANIMAL";
    InteractType[InteractType["INTERACT_TYPE_QUEST_GADGET"] = 14] = "INTERACT_TYPE_QUEST_GADGET";
    InteractType[InteractType["INTERACT_TYPE_Unk2700_LIEIKFDFMGF"] = 15] = "INTERACT_TYPE_Unk2700_LIEIKFDFMGF";
    InteractType[InteractType["INTERACT_TYPE_Unk3000_NMOCFKDNCOB"] = 16] = "INTERACT_TYPE_Unk3000_NMOCFKDNCOB";
})(InteractType = exports.InteractType || (exports.InteractType = {}));
