/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: LiveEndNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class LiveEndNotify extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        live_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("live_id" in data && data.live_id != undefined) {
                this.live_id = data.live_id;
            }
        }
    }
    get live_id() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set live_id(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    static fromObject(data: {
        live_id?: number;
    }): LiveEndNotify {
        const message = new LiveEndNotify({});
        if (data.live_id != null) {
            message.live_id = data.live_id;
        }
        return message;
    }
    toObject() {
        const data: {
            live_id?: number;
        } = {};
        if (this.live_id != null) {
            data.live_id = this.live_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.live_id != 0)
            writer.writeUint32(5, this.live_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LiveEndNotify {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new LiveEndNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 5:
                    message.live_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): LiveEndNotify {
        return LiveEndNotify.deserialize(bytes);
    }
}
