"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _LunaRiteTakeSacrificeRewardReq_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.LunaRiteTakeSacrificeRewardReq = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: LunaRiteTakeSacrificeRewardReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class LunaRiteTakeSacrificeRewardReq extends pb_1.Message {
    constructor(data) {
        super();
        _LunaRiteTakeSacrificeRewardReq_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _LunaRiteTakeSacrificeRewardReq_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("area_id" in data && data.area_id != undefined) {
                this.area_id = data.area_id;
            }
            if ("index" in data && data.index != undefined) {
                this.index = data.index;
            }
        }
    }
    get area_id() {
        return pb_1.Message.getFieldWithDefault(this, 11, 0);
    }
    set area_id(value) {
        pb_1.Message.setField(this, 11, value);
    }
    get index() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0);
    }
    set index(value) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data) {
        const message = new LunaRiteTakeSacrificeRewardReq({});
        if (data.area_id != null) {
            message.area_id = data.area_id;
        }
        if (data.index != null) {
            message.index = data.index;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.area_id != null) {
            data.area_id = this.area_id;
        }
        if (this.index != null) {
            data.index = this.index;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.area_id != 0)
            writer.writeUint32(11, this.area_id);
        if (this.index != 0)
            writer.writeUint32(3, this.index);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new LunaRiteTakeSacrificeRewardReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 11:
                    message.area_id = reader.readUint32();
                    break;
                case 3:
                    message.index = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return LunaRiteTakeSacrificeRewardReq.deserialize(bytes);
    }
}
exports.LunaRiteTakeSacrificeRewardReq = LunaRiteTakeSacrificeRewardReq;
_LunaRiteTakeSacrificeRewardReq_one_of_decls = new WeakMap();
