"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MapMarkPointType = void 0;
// @generated by protobuf-ts 2.8.2 with parameter output_typescript
// @generated from protobuf file "MapMarkPointType.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
/**
 * @generated from protobuf enum MapMarkPointType
 */
var MapMarkPointType;
(function (MapMarkPointType) {
    /**
     * @generated from protobuf enum value: MAP_MARK_POINT_TYPE_NPC = 0;
     */
    MapMarkPointType[MapMarkPointType["NPC"] = 0] = "NPC";
    /**
     * @generated from protobuf enum value: MAP_MARK_POINT_TYPE_QUEST = 1;
     */
    MapMarkPointType[MapMarkPointType["QUEST"] = 1] = "QUEST";
    /**
     * @generated from protobuf enum value: MAP_MARK_POINT_TYPE_SPECIAL = 2;
     */
    MapMarkPointType[MapMarkPointType["SPECIAL"] = 2] = "SPECIAL";
    /**
     * @generated from protobuf enum value: MAP_MARK_POINT_TYPE_MINE = 3;
     */
    MapMarkPointType[MapMarkPointType["MINE"] = 3] = "MINE";
    /**
     * @generated from protobuf enum value: MAP_MARK_POINT_TYPE_COLLECTION = 4;
     */
    MapMarkPointType[MapMarkPointType["COLLECTION"] = 4] = "COLLECTION";
    /**
     * @generated from protobuf enum value: MAP_MARK_POINT_TYPE_MONSTER = 5;
     */
    MapMarkPointType[MapMarkPointType["MONSTER"] = 5] = "MONSTER";
    /**
     * @generated from protobuf enum value: MAP_MARK_POINT_TYPE_FISH_POOL = 6;
     */
    MapMarkPointType[MapMarkPointType["FISH_POOL"] = 6] = "FISH_POOL";
})(MapMarkPointType = exports.MapMarkPointType || (exports.MapMarkPointType = {}));
