"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MotionState = void 0;
var MotionState;
(function (MotionState) {
    MotionState[MotionState["MOTION_STATE_NONE"] = 0] = "MOTION_STATE_NONE";
    MotionState[MotionState["MOTION_STATE_RESET"] = 1] = "MOTION_STATE_RESET";
    MotionState[MotionState["MOTION_STATE_STANDBY"] = 2] = "MOTION_STATE_STANDBY";
    MotionState[MotionState["MOTION_STATE_STANDBY_MOVE"] = 3] = "MOTION_STATE_STANDBY_MOVE";
    MotionState[MotionState["MOTION_STATE_WALK"] = 4] = "MOTION_STATE_WALK";
    MotionState[MotionState["MOTION_STATE_RUN"] = 5] = "MOTION_STATE_RUN";
    MotionState[MotionState["MOTION_STATE_DASH"] = 6] = "MOTION_STATE_DASH";
    MotionState[MotionState["MOTION_STATE_CLIMB"] = 7] = "MOTION_STATE_CLIMB";
    MotionState[MotionState["MOTION_STATE_CLIMB_JUMP"] = 8] = "MOTION_STATE_CLIMB_JUMP";
    MotionState[MotionState["MOTION_STATE_STANDBY_TO_CLIMB"] = 9] = "MOTION_STATE_STANDBY_TO_CLIMB";
    MotionState[MotionState["MOTION_STATE_FIGHT"] = 10] = "MOTION_STATE_FIGHT";
    MotionState[MotionState["MOTION_STATE_JUMP"] = 11] = "MOTION_STATE_JUMP";
    MotionState[MotionState["MOTION_STATE_DROP"] = 12] = "MOTION_STATE_DROP";
    MotionState[MotionState["MOTION_STATE_FLY"] = 13] = "MOTION_STATE_FLY";
    MotionState[MotionState["MOTION_STATE_SWIM_MOVE"] = 14] = "MOTION_STATE_SWIM_MOVE";
    MotionState[MotionState["MOTION_STATE_SWIM_IDLE"] = 15] = "MOTION_STATE_SWIM_IDLE";
    MotionState[MotionState["MOTION_STATE_SWIM_DASH"] = 16] = "MOTION_STATE_SWIM_DASH";
    MotionState[MotionState["MOTION_STATE_SWIM_JUMP"] = 17] = "MOTION_STATE_SWIM_JUMP";
    MotionState[MotionState["MOTION_STATE_SLIP"] = 18] = "MOTION_STATE_SLIP";
    MotionState[MotionState["MOTION_STATE_GO_UPSTAIRS"] = 19] = "MOTION_STATE_GO_UPSTAIRS";
    MotionState[MotionState["MOTION_STATE_FALL_ON_GROUND"] = 20] = "MOTION_STATE_FALL_ON_GROUND";
    MotionState[MotionState["MOTION_STATE_JUMP_UP_WALL_FOR_STANDBY"] = 21] = "MOTION_STATE_JUMP_UP_WALL_FOR_STANDBY";
    MotionState[MotionState["MOTION_STATE_JUMP_OFF_WALL"] = 22] = "MOTION_STATE_JUMP_OFF_WALL";
    MotionState[MotionState["MOTION_STATE_POWERED_FLY"] = 23] = "MOTION_STATE_POWERED_FLY";
    MotionState[MotionState["MOTION_STATE_LADDER_IDLE"] = 24] = "MOTION_STATE_LADDER_IDLE";
    MotionState[MotionState["MOTION_STATE_LADDER_MOVE"] = 25] = "MOTION_STATE_LADDER_MOVE";
    MotionState[MotionState["MOTION_STATE_LADDER_SLIP"] = 26] = "MOTION_STATE_LADDER_SLIP";
    MotionState[MotionState["MOTION_STATE_STANDBY_TO_LADDER"] = 27] = "MOTION_STATE_STANDBY_TO_LADDER";
    MotionState[MotionState["MOTION_STATE_LADDER_TO_STANDBY"] = 28] = "MOTION_STATE_LADDER_TO_STANDBY";
    MotionState[MotionState["MOTION_STATE_DANGER_STANDBY"] = 29] = "MOTION_STATE_DANGER_STANDBY";
    MotionState[MotionState["MOTION_STATE_DANGER_STANDBY_MOVE"] = 30] = "MOTION_STATE_DANGER_STANDBY_MOVE";
    MotionState[MotionState["MOTION_STATE_DANGER_WALK"] = 31] = "MOTION_STATE_DANGER_WALK";
    MotionState[MotionState["MOTION_STATE_DANGER_RUN"] = 32] = "MOTION_STATE_DANGER_RUN";
    MotionState[MotionState["MOTION_STATE_DANGER_DASH"] = 33] = "MOTION_STATE_DANGER_DASH";
    MotionState[MotionState["MOTION_STATE_CROUCH_IDLE"] = 34] = "MOTION_STATE_CROUCH_IDLE";
    MotionState[MotionState["MOTION_STATE_CROUCH_MOVE"] = 35] = "MOTION_STATE_CROUCH_MOVE";
    MotionState[MotionState["MOTION_STATE_CROUCH_ROLL"] = 36] = "MOTION_STATE_CROUCH_ROLL";
    MotionState[MotionState["MOTION_STATE_NOTIFY"] = 37] = "MOTION_STATE_NOTIFY";
    MotionState[MotionState["MOTION_STATE_LAND_SPEED"] = 38] = "MOTION_STATE_LAND_SPEED";
    MotionState[MotionState["MOTION_STATE_MOVE_FAIL_ACK"] = 39] = "MOTION_STATE_MOVE_FAIL_ACK";
    MotionState[MotionState["MOTION_STATE_WATERFALL"] = 40] = "MOTION_STATE_WATERFALL";
    MotionState[MotionState["MOTION_STATE_DASH_BEFORE_SHAKE"] = 41] = "MOTION_STATE_DASH_BEFORE_SHAKE";
    MotionState[MotionState["MOTION_STATE_SIT_IDLE"] = 42] = "MOTION_STATE_SIT_IDLE";
    MotionState[MotionState["MOTION_STATE_FORCE_SET_POS"] = 43] = "MOTION_STATE_FORCE_SET_POS";
    MotionState[MotionState["MOTION_STATE_QUEST_FORCE_DRAG"] = 44] = "MOTION_STATE_QUEST_FORCE_DRAG";
    MotionState[MotionState["MOTION_STATE_FOLLOW_ROUTE"] = 45] = "MOTION_STATE_FOLLOW_ROUTE";
    MotionState[MotionState["MOTION_STATE_SKIFF_BOARDING"] = 46] = "MOTION_STATE_SKIFF_BOARDING";
    MotionState[MotionState["MOTION_STATE_SKIFF_NORMAL"] = 47] = "MOTION_STATE_SKIFF_NORMAL";
    MotionState[MotionState["MOTION_STATE_SKIFF_DASH"] = 48] = "MOTION_STATE_SKIFF_DASH";
    MotionState[MotionState["MOTION_STATE_SKIFF_POWERED_DASH"] = 49] = "MOTION_STATE_SKIFF_POWERED_DASH";
    MotionState[MotionState["MOTION_STATE_DESTROY_VEHICLE"] = 50] = "MOTION_STATE_DESTROY_VEHICLE";
    MotionState[MotionState["MOTION_STATE_FLY_IDLE"] = 51] = "MOTION_STATE_FLY_IDLE";
    MotionState[MotionState["MOTION_STATE_FLY_SLOW"] = 52] = "MOTION_STATE_FLY_SLOW";
    MotionState[MotionState["MOTION_STATE_FLY_FAST"] = 53] = "MOTION_STATE_FLY_FAST";
    MotionState[MotionState["MOTION_STATE_NUM"] = 54] = "MOTION_STATE_NUM";
    MotionState[MotionState["MOTION_STATE_Unk2700_OOFNNHKLEFE"] = 55] = "MOTION_STATE_Unk2700_OOFNNHKLEFE";
    MotionState[MotionState["MOTION_STATE_Unk2700_KMIGLMEGNOK"] = 56] = "MOTION_STATE_Unk2700_KMIGLMEGNOK";
})(MotionState = exports.MotionState || (exports.MotionState = {}));
