/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: ProjectorOptionReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class ProjectorOptionReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        op_type?: number;
        entity_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("op_type" in data && data.op_type != undefined) {
                this.op_type = data.op_type;
            }
            if ("entity_id" in data && data.entity_id != undefined) {
                this.entity_id = data.entity_id;
            }
        }
    }
    get op_type() {
        return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
    }
    set op_type(value: number) {
        pb_1.Message.setField(this, 7, value);
    }
    get entity_id() {
        return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
    }
    set entity_id(value: number) {
        pb_1.Message.setField(this, 10, value);
    }
    static fromObject(data: {
        op_type?: number;
        entity_id?: number;
    }): ProjectorOptionReq {
        const message = new ProjectorOptionReq({});
        if (data.op_type != null) {
            message.op_type = data.op_type;
        }
        if (data.entity_id != null) {
            message.entity_id = data.entity_id;
        }
        return message;
    }
    toObject() {
        const data: {
            op_type?: number;
            entity_id?: number;
        } = {};
        if (this.op_type != null) {
            data.op_type = this.op_type;
        }
        if (this.entity_id != null) {
            data.entity_id = this.entity_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.op_type != 0)
            writer.writeUint32(7, this.op_type);
        if (this.entity_id != 0)
            writer.writeUint32(10, this.entity_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProjectorOptionReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProjectorOptionReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 7:
                    message.op_type = reader.readUint32();
                    break;
                case 10:
                    message.entity_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ProjectorOptionReq {
        return ProjectorOptionReq.deserialize(bytes);
    }
}
export namespace ProjectorOptionReq {
    export enum ProjectorOpType {
        PROJECTOR_OP_TYPE_NONE = 0,
        PROJECTOR_OP_TYPE_CREATE = 1,
        PROJECTOR_OP_TYPE_DESTROY = 2
    }
}
