/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: ProudSkillUpgradeReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class ProudSkillUpgradeReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        avatar_guid?: number;
        old_proud_skill_level?: number;
        proud_skill_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("avatar_guid" in data && data.avatar_guid != undefined) {
                this.avatar_guid = data.avatar_guid;
            }
            if ("old_proud_skill_level" in data && data.old_proud_skill_level != undefined) {
                this.old_proud_skill_level = data.old_proud_skill_level;
            }
            if ("proud_skill_id" in data && data.proud_skill_id != undefined) {
                this.proud_skill_id = data.proud_skill_id;
            }
        }
    }
    get avatar_guid() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set avatar_guid(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    get old_proud_skill_level() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set old_proud_skill_level(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    get proud_skill_id() {
        return pb_1.Message.getFieldWithDefault(this, 14, 0) as number;
    }
    set proud_skill_id(value: number) {
        pb_1.Message.setField(this, 14, value);
    }
    static fromObject(data: {
        avatar_guid?: number;
        old_proud_skill_level?: number;
        proud_skill_id?: number;
    }): ProudSkillUpgradeReq {
        const message = new ProudSkillUpgradeReq({});
        if (data.avatar_guid != null) {
            message.avatar_guid = data.avatar_guid;
        }
        if (data.old_proud_skill_level != null) {
            message.old_proud_skill_level = data.old_proud_skill_level;
        }
        if (data.proud_skill_id != null) {
            message.proud_skill_id = data.proud_skill_id;
        }
        return message;
    }
    toObject() {
        const data: {
            avatar_guid?: number;
            old_proud_skill_level?: number;
            proud_skill_id?: number;
        } = {};
        if (this.avatar_guid != null) {
            data.avatar_guid = this.avatar_guid;
        }
        if (this.old_proud_skill_level != null) {
            data.old_proud_skill_level = this.old_proud_skill_level;
        }
        if (this.proud_skill_id != null) {
            data.proud_skill_id = this.proud_skill_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.avatar_guid != 0)
            writer.writeUint64(5, this.avatar_guid);
        if (this.old_proud_skill_level != 0)
            writer.writeUint32(4, this.old_proud_skill_level);
        if (this.proud_skill_id != 0)
            writer.writeUint32(14, this.proud_skill_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProudSkillUpgradeReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProudSkillUpgradeReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 5:
                    message.avatar_guid = reader.readUint64();
                    break;
                case 4:
                    message.old_proud_skill_level = reader.readUint32();
                    break;
                case 14:
                    message.proud_skill_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ProudSkillUpgradeReq {
        return ProudSkillUpgradeReq.deserialize(bytes);
    }
}
