"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _QuestDestroyNpcReq_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.QuestDestroyNpcReq = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: QuestDestroyNpcReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class QuestDestroyNpcReq extends pb_1.Message {
    constructor(data) {
        super();
        _QuestDestroyNpcReq_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _QuestDestroyNpcReq_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("npc_id" in data && data.npc_id != undefined) {
                this.npc_id = data.npc_id;
            }
            if ("parent_quest_id" in data && data.parent_quest_id != undefined) {
                this.parent_quest_id = data.parent_quest_id;
            }
        }
    }
    get npc_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0);
    }
    set npc_id(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get parent_quest_id() {
        return pb_1.Message.getFieldWithDefault(this, 12, 0);
    }
    set parent_quest_id(value) {
        pb_1.Message.setField(this, 12, value);
    }
    static fromObject(data) {
        const message = new QuestDestroyNpcReq({});
        if (data.npc_id != null) {
            message.npc_id = data.npc_id;
        }
        if (data.parent_quest_id != null) {
            message.parent_quest_id = data.parent_quest_id;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.npc_id != null) {
            data.npc_id = this.npc_id;
        }
        if (this.parent_quest_id != null) {
            data.parent_quest_id = this.parent_quest_id;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.npc_id != 0)
            writer.writeUint32(1, this.npc_id);
        if (this.parent_quest_id != 0)
            writer.writeUint32(12, this.parent_quest_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QuestDestroyNpcReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.npc_id = reader.readUint32();
                    break;
                case 12:
                    message.parent_quest_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return QuestDestroyNpcReq.deserialize(bytes);
    }
}
exports.QuestDestroyNpcReq = QuestDestroyNpcReq;
_QuestDestroyNpcReq_one_of_decls = new WeakMap();
