// @generated by protobuf-ts 2.8.2 with parameter output_typescript
// @generated from protobuf file "RecordUsage.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
/**
 * @generated from protobuf enum RecordUsage
 */
export enum RecordUsage {
    /**
     * @generated from protobuf enum value: RECORD_USAGE_UGC_RECORD_USAGE_NONE = 0;
     */
    UGC_RECORD_USAGE_NONE = 0,
    /**
     * @generated from protobuf enum value: RECORD_USAGE_UGC_RECORD_USAGE_IMPORT = 1;
     */
    UGC_RECORD_USAGE_IMPORT = 1,
    /**
     * @generated from protobuf enum value: RECORD_USAGE_UGC_RECORD_USAGE_PLAY = 2;
     */
    UGC_RECORD_USAGE_PLAY = 2,
    /**
     * @generated from protobuf enum value: RECORD_USAGE_UGC_RECORD_USAGE_TRIAL = 3;
     */
    UGC_RECORD_USAGE_TRIAL = 3,
    /**
     * @generated from protobuf enum value: RECORD_USAGE_UGC_RECORD_USAGE_COMPARE = 4;
     */
    UGC_RECORD_USAGE_COMPARE = 4
}
