"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _RegionSearchChangeRegionNotify_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegionSearchChangeRegionNotify = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: RegionSearchChangeRegionNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class RegionSearchChangeRegionNotify extends pb_1.Message {
    constructor(data) {
        super();
        _RegionSearchChangeRegionNotify_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _RegionSearchChangeRegionNotify_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("event" in data && data.event != undefined) {
                this.event = data.event;
            }
            if ("region_id" in data && data.region_id != undefined) {
                this.region_id = data.region_id;
            }
        }
    }
    get event() {
        return pb_1.Message.getFieldWithDefault(this, 1, RegionSearchChangeRegionNotify.RegionEvent.REGION_EVENT_NONE);
    }
    set event(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get region_id() {
        return pb_1.Message.getFieldWithDefault(this, 10, 0);
    }
    set region_id(value) {
        pb_1.Message.setField(this, 10, value);
    }
    static fromObject(data) {
        const message = new RegionSearchChangeRegionNotify({});
        if (data.event != null) {
            message.event = data.event;
        }
        if (data.region_id != null) {
            message.region_id = data.region_id;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.event != null) {
            data.event = this.event;
        }
        if (this.region_id != null) {
            data.region_id = this.region_id;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.event != RegionSearchChangeRegionNotify.RegionEvent.REGION_EVENT_NONE)
            writer.writeEnum(1, this.event);
        if (this.region_id != 0)
            writer.writeUint32(10, this.region_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RegionSearchChangeRegionNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.event = reader.readEnum();
                    break;
                case 10:
                    message.region_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return RegionSearchChangeRegionNotify.deserialize(bytes);
    }
}
exports.RegionSearchChangeRegionNotify = RegionSearchChangeRegionNotify;
_RegionSearchChangeRegionNotify_one_of_decls = new WeakMap();
(function (RegionSearchChangeRegionNotify) {
    let RegionEvent;
    (function (RegionEvent) {
        RegionEvent[RegionEvent["REGION_EVENT_NONE"] = 0] = "REGION_EVENT_NONE";
        RegionEvent[RegionEvent["REGION_EVENT_ENTER"] = 1] = "REGION_EVENT_ENTER";
        RegionEvent[RegionEvent["REGION_EVENT_LEAVE"] = 2] = "REGION_EVENT_LEAVE";
    })(RegionEvent = RegionSearchChangeRegionNotify.RegionEvent || (RegionSearchChangeRegionNotify.RegionEvent = {}));
})(RegionSearchChangeRegionNotify = exports.RegionSearchChangeRegionNotify || (exports.RegionSearchChangeRegionNotify = {}));
