/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: Reward.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./ItemParam";
import * as pb_1 from "google-protobuf";
export class Reward extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        reward_id?: number;
        item_list?: dependency_1.ItemParam[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("reward_id" in data && data.reward_id != undefined) {
                this.reward_id = data.reward_id;
            }
            if ("item_list" in data && data.item_list != undefined) {
                this.item_list = data.item_list;
            }
        }
    }
    get reward_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set reward_id(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get item_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.ItemParam, 2) as dependency_1.ItemParam[];
    }
    set item_list(value: dependency_1.ItemParam[]) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    static fromObject(data: {
        reward_id?: number;
        item_list?: ReturnType<typeof dependency_1.ItemParam.prototype.toObject>[];
    }): Reward {
        const message = new Reward({});
        if (data.reward_id != null) {
            message.reward_id = data.reward_id;
        }
        if (data.item_list != null) {
            message.item_list = data.item_list.map(item => dependency_1.ItemParam.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            reward_id?: number;
            item_list?: ReturnType<typeof dependency_1.ItemParam.prototype.toObject>[];
        } = {};
        if (this.reward_id != null) {
            data.reward_id = this.reward_id;
        }
        if (this.item_list != null) {
            data.item_list = this.item_list.map((item: dependency_1.ItemParam) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.reward_id != 0)
            writer.writeUint32(1, this.reward_id);
        if (this.item_list.length)
            writer.writeRepeatedMessage(2, this.item_list, (item: dependency_1.ItemParam) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Reward {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Reward();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.reward_id = reader.readUint32();
                    break;
                case 2:
                    reader.readMessage(message.item_list, () => pb_1.Message.addToRepeatedWrapperField(message, 2, dependency_1.ItemParam.deserialize(reader), dependency_1.ItemParam));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Reward {
        return Reward.deserialize(bytes);
    }
}
