/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: ScenePlayInviteResultNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class ScenePlayInviteResultNotify extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        is_all_argee?: boolean;
        play_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("is_all_argee" in data && data.is_all_argee != undefined) {
                this.is_all_argee = data.is_all_argee;
            }
            if ("play_id" in data && data.play_id != undefined) {
                this.play_id = data.play_id;
            }
        }
    }
    get is_all_argee() {
        return pb_1.Message.getFieldWithDefault(this, 11, false) as boolean;
    }
    set is_all_argee(value: boolean) {
        pb_1.Message.setField(this, 11, value);
    }
    get play_id() {
        return pb_1.Message.getFieldWithDefault(this, 15, 0) as number;
    }
    set play_id(value: number) {
        pb_1.Message.setField(this, 15, value);
    }
    static fromObject(data: {
        is_all_argee?: boolean;
        play_id?: number;
    }): ScenePlayInviteResultNotify {
        const message = new ScenePlayInviteResultNotify({});
        if (data.is_all_argee != null) {
            message.is_all_argee = data.is_all_argee;
        }
        if (data.play_id != null) {
            message.play_id = data.play_id;
        }
        return message;
    }
    toObject() {
        const data: {
            is_all_argee?: boolean;
            play_id?: number;
        } = {};
        if (this.is_all_argee != null) {
            data.is_all_argee = this.is_all_argee;
        }
        if (this.play_id != null) {
            data.play_id = this.play_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.is_all_argee != false)
            writer.writeBool(11, this.is_all_argee);
        if (this.play_id != 0)
            writer.writeUint32(15, this.play_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ScenePlayInviteResultNotify {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ScenePlayInviteResultNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 11:
                    message.is_all_argee = reader.readBool();
                    break;
                case 15:
                    message.play_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ScenePlayInviteResultNotify {
        return ScenePlayInviteResultNotify.deserialize(bytes);
    }
}
