/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: SceneGalleryFlowerInfo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class SceneGalleryFlowerInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        end_time?: number;
        target_score?: number;
        cur_score?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("end_time" in data && data.end_time != undefined) {
                this.end_time = data.end_time;
            }
            if ("target_score" in data && data.target_score != undefined) {
                this.target_score = data.target_score;
            }
            if ("cur_score" in data && data.cur_score != undefined) {
                this.cur_score = data.cur_score;
            }
        }
    }
    get end_time() {
        return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
    }
    set end_time(value: number) {
        pb_1.Message.setField(this, 7, value);
    }
    get target_score() {
        return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
    }
    set target_score(value: number) {
        pb_1.Message.setField(this, 13, value);
    }
    get cur_score() {
        return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
    }
    set cur_score(value: number) {
        pb_1.Message.setField(this, 9, value);
    }
    static fromObject(data: {
        end_time?: number;
        target_score?: number;
        cur_score?: number;
    }): SceneGalleryFlowerInfo {
        const message = new SceneGalleryFlowerInfo({});
        if (data.end_time != null) {
            message.end_time = data.end_time;
        }
        if (data.target_score != null) {
            message.target_score = data.target_score;
        }
        if (data.cur_score != null) {
            message.cur_score = data.cur_score;
        }
        return message;
    }
    toObject() {
        const data: {
            end_time?: number;
            target_score?: number;
            cur_score?: number;
        } = {};
        if (this.end_time != null) {
            data.end_time = this.end_time;
        }
        if (this.target_score != null) {
            data.target_score = this.target_score;
        }
        if (this.cur_score != null) {
            data.cur_score = this.cur_score;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.end_time != 0)
            writer.writeUint32(7, this.end_time);
        if (this.target_score != 0)
            writer.writeUint32(13, this.target_score);
        if (this.cur_score != 0)
            writer.writeUint32(9, this.cur_score);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SceneGalleryFlowerInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SceneGalleryFlowerInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 7:
                    message.end_time = reader.readUint32();
                    break;
                case 13:
                    message.target_score = reader.readUint32();
                    break;
                case 9:
                    message.cur_score = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SceneGalleryFlowerInfo {
        return SceneGalleryFlowerInfo.deserialize(bytes);
    }
}
