// @generated by protobuf-ts 2.8.2 with parameter output_typescript
// @generated from protobuf file "SegmentInfo.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message SegmentInfo
 */
export interface SegmentInfo {
    /**
     * @generated from protobuf field: uint32 module = 1;
     */
    module: number;
    /**
     * @generated from protobuf field: uint32 size = 7;
     */
    size: number;
    /**
     * @generated from protobuf field: uint32 offset = 11;
     */
    offset: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class SegmentInfo$Type extends MessageType<SegmentInfo> {
    constructor() {
        super("SegmentInfo", [
            { no: 1, name: "module", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "size", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "offset", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<SegmentInfo>): SegmentInfo {
        const message = { module: 0, size: 0, offset: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SegmentInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SegmentInfo): SegmentInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 module */ 1:
                    message.module = reader.uint32();
                    break;
                case /* uint32 size */ 7:
                    message.size = reader.uint32();
                    break;
                case /* uint32 offset */ 11:
                    message.offset = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SegmentInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 module = 1; */
        if (message.module !== 0)
            writer.tag(1, WireType.Varint).uint32(message.module);
        /* uint32 size = 7; */
        if (message.size !== 0)
            writer.tag(7, WireType.Varint).uint32(message.size);
        /* uint32 offset = 11; */
        if (message.offset !== 0)
            writer.tag(11, WireType.Varint).uint32(message.offset);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message SegmentInfo
 */
export const SegmentInfo = new SegmentInfo$Type();
