"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _SumoAvatarInfo_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.SumoAvatarInfo = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: SumoAvatarInfo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class SumoAvatarInfo extends pb_1.Message {
    constructor(data) {
        super();
        _SumoAvatarInfo_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _SumoAvatarInfo_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("is_trial" in data && data.is_trial != undefined) {
                this.is_trial = data.is_trial;
            }
            if ("avatar_id" in data && data.avatar_id != undefined) {
                this.avatar_id = data.avatar_id;
            }
        }
    }
    get is_trial() {
        return pb_1.Message.getFieldWithDefault(this, 2, false);
    }
    set is_trial(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get avatar_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0);
    }
    set avatar_id(value) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data) {
        const message = new SumoAvatarInfo({});
        if (data.is_trial != null) {
            message.is_trial = data.is_trial;
        }
        if (data.avatar_id != null) {
            message.avatar_id = data.avatar_id;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.is_trial != null) {
            data.is_trial = this.is_trial;
        }
        if (this.avatar_id != null) {
            data.avatar_id = this.avatar_id;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.is_trial != false)
            writer.writeBool(2, this.is_trial);
        if (this.avatar_id != 0)
            writer.writeUint64(1, this.avatar_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SumoAvatarInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.is_trial = reader.readBool();
                    break;
                case 1:
                    message.avatar_id = reader.readUint64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return SumoAvatarInfo.deserialize(bytes);
    }
}
exports.SumoAvatarInfo = SumoAvatarInfo;
_SumoAvatarInfo_one_of_decls = new WeakMap();
