/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: TakeBattlePassRewardRsp.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./BattlePassRewardTakeOption";
import * as dependency_2 from "./ItemParam";
import * as pb_1 from "google-protobuf";
export class TakeBattlePassRewardRsp extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        item_list?: dependency_2.ItemParam[];
        retcode?: number;
        take_option_list?: dependency_1.BattlePassRewardTakeOption[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 9], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("item_list" in data && data.item_list != undefined) {
                this.item_list = data.item_list;
            }
            if ("retcode" in data && data.retcode != undefined) {
                this.retcode = data.retcode;
            }
            if ("take_option_list" in data && data.take_option_list != undefined) {
                this.take_option_list = data.take_option_list;
            }
        }
    }
    get item_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_2.ItemParam, 7) as dependency_2.ItemParam[];
    }
    set item_list(value: dependency_2.ItemParam[]) {
        pb_1.Message.setRepeatedWrapperField(this, 7, value);
    }
    get retcode() {
        return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
    }
    set retcode(value: number) {
        pb_1.Message.setField(this, 13, value);
    }
    get take_option_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.BattlePassRewardTakeOption, 9) as dependency_1.BattlePassRewardTakeOption[];
    }
    set take_option_list(value: dependency_1.BattlePassRewardTakeOption[]) {
        pb_1.Message.setRepeatedWrapperField(this, 9, value);
    }
    static fromObject(data: {
        item_list?: ReturnType<typeof dependency_2.ItemParam.prototype.toObject>[];
        retcode?: number;
        take_option_list?: ReturnType<typeof dependency_1.BattlePassRewardTakeOption.prototype.toObject>[];
    }): TakeBattlePassRewardRsp {
        const message = new TakeBattlePassRewardRsp({});
        if (data.item_list != null) {
            message.item_list = data.item_list.map(item => dependency_2.ItemParam.fromObject(item));
        }
        if (data.retcode != null) {
            message.retcode = data.retcode;
        }
        if (data.take_option_list != null) {
            message.take_option_list = data.take_option_list.map(item => dependency_1.BattlePassRewardTakeOption.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            item_list?: ReturnType<typeof dependency_2.ItemParam.prototype.toObject>[];
            retcode?: number;
            take_option_list?: ReturnType<typeof dependency_1.BattlePassRewardTakeOption.prototype.toObject>[];
        } = {};
        if (this.item_list != null) {
            data.item_list = this.item_list.map((item: dependency_2.ItemParam) => item.toObject());
        }
        if (this.retcode != null) {
            data.retcode = this.retcode;
        }
        if (this.take_option_list != null) {
            data.take_option_list = this.take_option_list.map((item: dependency_1.BattlePassRewardTakeOption) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.item_list.length)
            writer.writeRepeatedMessage(7, this.item_list, (item: dependency_2.ItemParam) => item.serialize(writer));
        if (this.retcode != 0)
            writer.writeInt32(13, this.retcode);
        if (this.take_option_list.length)
            writer.writeRepeatedMessage(9, this.take_option_list, (item: dependency_1.BattlePassRewardTakeOption) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TakeBattlePassRewardRsp {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TakeBattlePassRewardRsp();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 7:
                    reader.readMessage(message.item_list, () => pb_1.Message.addToRepeatedWrapperField(message, 7, dependency_2.ItemParam.deserialize(reader), dependency_2.ItemParam));
                    break;
                case 13:
                    message.retcode = reader.readInt32();
                    break;
                case 9:
                    reader.readMessage(message.take_option_list, () => pb_1.Message.addToRepeatedWrapperField(message, 9, dependency_1.BattlePassRewardTakeOption.deserialize(reader), dependency_1.BattlePassRewardTakeOption));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): TakeBattlePassRewardRsp {
        return TakeBattlePassRewardRsp.deserialize(bytes);
    }
}
