/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: TakeCompoundOutputReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class TakeCompoundOutputReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        compound_group_id?: number;
        compound_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("compound_group_id" in data && data.compound_group_id != undefined) {
                this.compound_group_id = data.compound_group_id;
            }
            if ("compound_id" in data && data.compound_id != undefined) {
                this.compound_id = data.compound_id;
            }
        }
    }
    get compound_group_id() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set compound_group_id(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get compound_id() {
        return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
    }
    set compound_id(value: number) {
        pb_1.Message.setField(this, 10, value);
    }
    static fromObject(data: {
        compound_group_id?: number;
        compound_id?: number;
    }): TakeCompoundOutputReq {
        const message = new TakeCompoundOutputReq({});
        if (data.compound_group_id != null) {
            message.compound_group_id = data.compound_group_id;
        }
        if (data.compound_id != null) {
            message.compound_id = data.compound_id;
        }
        return message;
    }
    toObject() {
        const data: {
            compound_group_id?: number;
            compound_id?: number;
        } = {};
        if (this.compound_group_id != null) {
            data.compound_group_id = this.compound_group_id;
        }
        if (this.compound_id != null) {
            data.compound_id = this.compound_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.compound_group_id != 0)
            writer.writeUint32(3, this.compound_group_id);
        if (this.compound_id != 0)
            writer.writeUint32(10, this.compound_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TakeCompoundOutputReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TakeCompoundOutputReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 3:
                    message.compound_group_id = reader.readUint32();
                    break;
                case 10:
                    message.compound_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): TakeCompoundOutputReq {
        return TakeCompoundOutputReq.deserialize(bytes);
    }
}
