"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _TakeEffigyRewardReq_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.TakeEffigyRewardReq = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: TakeEffigyRewardReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = require("google-protobuf");
class TakeEffigyRewardReq extends pb_1.Message {
    constructor(data) {
        super();
        _TakeEffigyRewardReq_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _TakeEffigyRewardReq_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("reward_index" in data && data.reward_index != undefined) {
                this.reward_index = data.reward_index;
            }
        }
    }
    get reward_index() {
        return pb_1.Message.getFieldWithDefault(this, 14, 0);
    }
    set reward_index(value) {
        pb_1.Message.setField(this, 14, value);
    }
    static fromObject(data) {
        const message = new TakeEffigyRewardReq({});
        if (data.reward_index != null) {
            message.reward_index = data.reward_index;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.reward_index != null) {
            data.reward_index = this.reward_index;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.reward_index != 0)
            writer.writeUint32(14, this.reward_index);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TakeEffigyRewardReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 14:
                    message.reward_index = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return TakeEffigyRewardReq.deserialize(bytes);
    }
}
exports.TakeEffigyRewardReq = TakeEffigyRewardReq;
_TakeEffigyRewardReq_one_of_decls = new WeakMap();
