/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: TakeOfferingLevelRewardReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class TakeOfferingLevelRewardReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        level?: number;
        offering_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("level" in data && data.level != undefined) {
                this.level = data.level;
            }
            if ("offering_id" in data && data.offering_id != undefined) {
                this.offering_id = data.offering_id;
            }
        }
    }
    get level() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set level(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    get offering_id() {
        return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
    }
    set offering_id(value: number) {
        pb_1.Message.setField(this, 11, value);
    }
    static fromObject(data: {
        level?: number;
        offering_id?: number;
    }): TakeOfferingLevelRewardReq {
        const message = new TakeOfferingLevelRewardReq({});
        if (data.level != null) {
            message.level = data.level;
        }
        if (data.offering_id != null) {
            message.offering_id = data.offering_id;
        }
        return message;
    }
    toObject() {
        const data: {
            level?: number;
            offering_id?: number;
        } = {};
        if (this.level != null) {
            data.level = this.level;
        }
        if (this.offering_id != null) {
            data.offering_id = this.offering_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.level != 0)
            writer.writeUint32(6, this.level);
        if (this.offering_id != 0)
            writer.writeUint32(11, this.offering_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TakeOfferingLevelRewardReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TakeOfferingLevelRewardReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 6:
                    message.level = reader.readUint32();
                    break;
                case 11:
                    message.offering_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): TakeOfferingLevelRewardReq {
        return TakeOfferingLevelRewardReq.deserialize(bytes);
    }
}
