/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: TowerEnterLevelReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class TowerEnterLevelReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        enter_point_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("enter_point_id" in data && data.enter_point_id != undefined) {
                this.enter_point_id = data.enter_point_id;
            }
        }
    }
    get enter_point_id() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set enter_point_id(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        enter_point_id?: number;
    }): TowerEnterLevelReq {
        const message = new TowerEnterLevelReq({});
        if (data.enter_point_id != null) {
            message.enter_point_id = data.enter_point_id;
        }
        return message;
    }
    toObject() {
        const data: {
            enter_point_id?: number;
        } = {};
        if (this.enter_point_id != null) {
            data.enter_point_id = this.enter_point_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.enter_point_id != 0)
            writer.writeUint32(3, this.enter_point_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TowerEnterLevelReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TowerEnterLevelReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 3:
                    message.enter_point_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): TowerEnterLevelReq {
        return TowerEnterLevelReq.deserialize(bytes);
    }
}
