"use strict";
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _TowerFloorRecordChangeNotify_one_of_decls;
Object.defineProperty(exports, "__esModule", { value: true });
exports.TowerFloorRecordChangeNotify = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: TowerFloorRecordChangeNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const dependency_1 = require("./TowerFloorRecord");
const pb_1 = require("google-protobuf");
class TowerFloorRecordChangeNotify extends pb_1.Message {
    constructor(data) {
        super();
        _TowerFloorRecordChangeNotify_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [8], __classPrivateFieldGet(this, _TowerFloorRecordChangeNotify_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("is_finished_entrance_floor" in data && data.is_finished_entrance_floor != undefined) {
                this.is_finished_entrance_floor = data.is_finished_entrance_floor;
            }
            if ("tower_floor_record_list" in data && data.tower_floor_record_list != undefined) {
                this.tower_floor_record_list = data.tower_floor_record_list;
            }
        }
    }
    get is_finished_entrance_floor() {
        return pb_1.Message.getFieldWithDefault(this, 11, false);
    }
    set is_finished_entrance_floor(value) {
        pb_1.Message.setField(this, 11, value);
    }
    get tower_floor_record_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.TowerFloorRecord, 8);
    }
    set tower_floor_record_list(value) {
        pb_1.Message.setRepeatedWrapperField(this, 8, value);
    }
    static fromObject(data) {
        const message = new TowerFloorRecordChangeNotify({});
        if (data.is_finished_entrance_floor != null) {
            message.is_finished_entrance_floor = data.is_finished_entrance_floor;
        }
        if (data.tower_floor_record_list != null) {
            message.tower_floor_record_list = data.tower_floor_record_list.map(item => dependency_1.TowerFloorRecord.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.is_finished_entrance_floor != null) {
            data.is_finished_entrance_floor = this.is_finished_entrance_floor;
        }
        if (this.tower_floor_record_list != null) {
            data.tower_floor_record_list = this.tower_floor_record_list.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.is_finished_entrance_floor != false)
            writer.writeBool(11, this.is_finished_entrance_floor);
        if (this.tower_floor_record_list.length)
            writer.writeRepeatedMessage(8, this.tower_floor_record_list, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TowerFloorRecordChangeNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 11:
                    message.is_finished_entrance_floor = reader.readBool();
                    break;
                case 8:
                    reader.readMessage(message.tower_floor_record_list, () => pb_1.Message.addToRepeatedWrapperField(message, 8, dependency_1.TowerFloorRecord.deserialize(reader), dependency_1.TowerFloorRecord));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return TowerFloorRecordChangeNotify.deserialize(bytes);
    }
}
exports.TowerFloorRecordChangeNotify = TowerFloorRecordChangeNotify;
_TowerFloorRecordChangeNotify_one_of_decls = new WeakMap();
