/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: TowerLevelStarCondData.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class TowerLevelStarCondData extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        Unk2700_HIFMJMAHEMB?: boolean;
        cond_value?: number;
        is_pause?: boolean;
        star_cond_index?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("Unk2700_HIFMJMAHEMB" in data && data.Unk2700_HIFMJMAHEMB != undefined) {
                this.Unk2700_HIFMJMAHEMB = data.Unk2700_HIFMJMAHEMB;
            }
            if ("cond_value" in data && data.cond_value != undefined) {
                this.cond_value = data.cond_value;
            }
            if ("is_pause" in data && data.is_pause != undefined) {
                this.is_pause = data.is_pause;
            }
            if ("star_cond_index" in data && data.star_cond_index != undefined) {
                this.star_cond_index = data.star_cond_index;
            }
        }
    }
    get Unk2700_HIFMJMAHEMB() {
        return pb_1.Message.getFieldWithDefault(this, 15, false) as boolean;
    }
    set Unk2700_HIFMJMAHEMB(value: boolean) {
        pb_1.Message.setField(this, 15, value);
    }
    get cond_value() {
        return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
    }
    set cond_value(value: number) {
        pb_1.Message.setField(this, 9, value);
    }
    get is_pause() {
        return pb_1.Message.getFieldWithDefault(this, 13, false) as boolean;
    }
    set is_pause(value: boolean) {
        pb_1.Message.setField(this, 13, value);
    }
    get star_cond_index() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set star_cond_index(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
        Unk2700_HIFMJMAHEMB?: boolean;
        cond_value?: number;
        is_pause?: boolean;
        star_cond_index?: number;
    }): TowerLevelStarCondData {
        const message = new TowerLevelStarCondData({});
        if (data.Unk2700_HIFMJMAHEMB != null) {
            message.Unk2700_HIFMJMAHEMB = data.Unk2700_HIFMJMAHEMB;
        }
        if (data.cond_value != null) {
            message.cond_value = data.cond_value;
        }
        if (data.is_pause != null) {
            message.is_pause = data.is_pause;
        }
        if (data.star_cond_index != null) {
            message.star_cond_index = data.star_cond_index;
        }
        return message;
    }
    toObject() {
        const data: {
            Unk2700_HIFMJMAHEMB?: boolean;
            cond_value?: number;
            is_pause?: boolean;
            star_cond_index?: number;
        } = {};
        if (this.Unk2700_HIFMJMAHEMB != null) {
            data.Unk2700_HIFMJMAHEMB = this.Unk2700_HIFMJMAHEMB;
        }
        if (this.cond_value != null) {
            data.cond_value = this.cond_value;
        }
        if (this.is_pause != null) {
            data.is_pause = this.is_pause;
        }
        if (this.star_cond_index != null) {
            data.star_cond_index = this.star_cond_index;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.Unk2700_HIFMJMAHEMB != false)
            writer.writeBool(15, this.Unk2700_HIFMJMAHEMB);
        if (this.cond_value != 0)
            writer.writeUint32(9, this.cond_value);
        if (this.is_pause != false)
            writer.writeBool(13, this.is_pause);
        if (this.star_cond_index != 0)
            writer.writeUint32(6, this.star_cond_index);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TowerLevelStarCondData {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TowerLevelStarCondData();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 15:
                    message.Unk2700_HIFMJMAHEMB = reader.readBool();
                    break;
                case 9:
                    message.cond_value = reader.readUint32();
                    break;
                case 13:
                    message.is_pause = reader.readBool();
                    break;
                case 6:
                    message.star_cond_index = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): TowerLevelStarCondData {
        return TowerLevelStarCondData.deserialize(bytes);
    }
}
