/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: TrackingIOInfo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class TrackingIOInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        Unk3300_KGGPDKGDELG?: string;
        Unk3300_PIBFPDAMJLE?: string;
        Unk3300_NMDNLHLAKAM?: string;
        Unk3300_GEJJKDLGFPH?: string;
        Unk3300_CNPIGDOEJPB?: string;
        Unk3300_CCOGBICMHKG?: string;
        Unk3300_DJHKHEFPCDK?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("Unk3300_KGGPDKGDELG" in data && data.Unk3300_KGGPDKGDELG != undefined) {
                this.Unk3300_KGGPDKGDELG = data.Unk3300_KGGPDKGDELG;
            }
            if ("Unk3300_PIBFPDAMJLE" in data && data.Unk3300_PIBFPDAMJLE != undefined) {
                this.Unk3300_PIBFPDAMJLE = data.Unk3300_PIBFPDAMJLE;
            }
            if ("Unk3300_NMDNLHLAKAM" in data && data.Unk3300_NMDNLHLAKAM != undefined) {
                this.Unk3300_NMDNLHLAKAM = data.Unk3300_NMDNLHLAKAM;
            }
            if ("Unk3300_GEJJKDLGFPH" in data && data.Unk3300_GEJJKDLGFPH != undefined) {
                this.Unk3300_GEJJKDLGFPH = data.Unk3300_GEJJKDLGFPH;
            }
            if ("Unk3300_CNPIGDOEJPB" in data && data.Unk3300_CNPIGDOEJPB != undefined) {
                this.Unk3300_CNPIGDOEJPB = data.Unk3300_CNPIGDOEJPB;
            }
            if ("Unk3300_CCOGBICMHKG" in data && data.Unk3300_CCOGBICMHKG != undefined) {
                this.Unk3300_CCOGBICMHKG = data.Unk3300_CCOGBICMHKG;
            }
            if ("Unk3300_DJHKHEFPCDK" in data && data.Unk3300_DJHKHEFPCDK != undefined) {
                this.Unk3300_DJHKHEFPCDK = data.Unk3300_DJHKHEFPCDK;
            }
        }
    }
    get Unk3300_KGGPDKGDELG() {
        return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
    }
    set Unk3300_KGGPDKGDELG(value: string) {
        pb_1.Message.setField(this, 10, value);
    }
    get Unk3300_PIBFPDAMJLE() {
        return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
    }
    set Unk3300_PIBFPDAMJLE(value: string) {
        pb_1.Message.setField(this, 12, value);
    }
    get Unk3300_NMDNLHLAKAM() {
        return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
    }
    set Unk3300_NMDNLHLAKAM(value: string) {
        pb_1.Message.setField(this, 7, value);
    }
    get Unk3300_GEJJKDLGFPH() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set Unk3300_GEJJKDLGFPH(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get Unk3300_CNPIGDOEJPB() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set Unk3300_CNPIGDOEJPB(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get Unk3300_CCOGBICMHKG() {
        return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
    }
    set Unk3300_CCOGBICMHKG(value: string) {
        pb_1.Message.setField(this, 9, value);
    }
    get Unk3300_DJHKHEFPCDK() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set Unk3300_DJHKHEFPCDK(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        Unk3300_KGGPDKGDELG?: string;
        Unk3300_PIBFPDAMJLE?: string;
        Unk3300_NMDNLHLAKAM?: string;
        Unk3300_GEJJKDLGFPH?: string;
        Unk3300_CNPIGDOEJPB?: string;
        Unk3300_CCOGBICMHKG?: string;
        Unk3300_DJHKHEFPCDK?: string;
    }): TrackingIOInfo {
        const message = new TrackingIOInfo({});
        if (data.Unk3300_KGGPDKGDELG != null) {
            message.Unk3300_KGGPDKGDELG = data.Unk3300_KGGPDKGDELG;
        }
        if (data.Unk3300_PIBFPDAMJLE != null) {
            message.Unk3300_PIBFPDAMJLE = data.Unk3300_PIBFPDAMJLE;
        }
        if (data.Unk3300_NMDNLHLAKAM != null) {
            message.Unk3300_NMDNLHLAKAM = data.Unk3300_NMDNLHLAKAM;
        }
        if (data.Unk3300_GEJJKDLGFPH != null) {
            message.Unk3300_GEJJKDLGFPH = data.Unk3300_GEJJKDLGFPH;
        }
        if (data.Unk3300_CNPIGDOEJPB != null) {
            message.Unk3300_CNPIGDOEJPB = data.Unk3300_CNPIGDOEJPB;
        }
        if (data.Unk3300_CCOGBICMHKG != null) {
            message.Unk3300_CCOGBICMHKG = data.Unk3300_CCOGBICMHKG;
        }
        if (data.Unk3300_DJHKHEFPCDK != null) {
            message.Unk3300_DJHKHEFPCDK = data.Unk3300_DJHKHEFPCDK;
        }
        return message;
    }
    toObject() {
        const data: {
            Unk3300_KGGPDKGDELG?: string;
            Unk3300_PIBFPDAMJLE?: string;
            Unk3300_NMDNLHLAKAM?: string;
            Unk3300_GEJJKDLGFPH?: string;
            Unk3300_CNPIGDOEJPB?: string;
            Unk3300_CCOGBICMHKG?: string;
            Unk3300_DJHKHEFPCDK?: string;
        } = {};
        if (this.Unk3300_KGGPDKGDELG != null) {
            data.Unk3300_KGGPDKGDELG = this.Unk3300_KGGPDKGDELG;
        }
        if (this.Unk3300_PIBFPDAMJLE != null) {
            data.Unk3300_PIBFPDAMJLE = this.Unk3300_PIBFPDAMJLE;
        }
        if (this.Unk3300_NMDNLHLAKAM != null) {
            data.Unk3300_NMDNLHLAKAM = this.Unk3300_NMDNLHLAKAM;
        }
        if (this.Unk3300_GEJJKDLGFPH != null) {
            data.Unk3300_GEJJKDLGFPH = this.Unk3300_GEJJKDLGFPH;
        }
        if (this.Unk3300_CNPIGDOEJPB != null) {
            data.Unk3300_CNPIGDOEJPB = this.Unk3300_CNPIGDOEJPB;
        }
        if (this.Unk3300_CCOGBICMHKG != null) {
            data.Unk3300_CCOGBICMHKG = this.Unk3300_CCOGBICMHKG;
        }
        if (this.Unk3300_DJHKHEFPCDK != null) {
            data.Unk3300_DJHKHEFPCDK = this.Unk3300_DJHKHEFPCDK;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.Unk3300_KGGPDKGDELG.length)
            writer.writeString(10, this.Unk3300_KGGPDKGDELG);
        if (this.Unk3300_PIBFPDAMJLE.length)
            writer.writeString(12, this.Unk3300_PIBFPDAMJLE);
        if (this.Unk3300_NMDNLHLAKAM.length)
            writer.writeString(7, this.Unk3300_NMDNLHLAKAM);
        if (this.Unk3300_GEJJKDLGFPH.length)
            writer.writeString(5, this.Unk3300_GEJJKDLGFPH);
        if (this.Unk3300_CNPIGDOEJPB.length)
            writer.writeString(2, this.Unk3300_CNPIGDOEJPB);
        if (this.Unk3300_CCOGBICMHKG.length)
            writer.writeString(9, this.Unk3300_CCOGBICMHKG);
        if (this.Unk3300_DJHKHEFPCDK.length)
            writer.writeString(1, this.Unk3300_DJHKHEFPCDK);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TrackingIOInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TrackingIOInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 10:
                    message.Unk3300_KGGPDKGDELG = reader.readString();
                    break;
                case 12:
                    message.Unk3300_PIBFPDAMJLE = reader.readString();
                    break;
                case 7:
                    message.Unk3300_NMDNLHLAKAM = reader.readString();
                    break;
                case 5:
                    message.Unk3300_GEJJKDLGFPH = reader.readString();
                    break;
                case 2:
                    message.Unk3300_CNPIGDOEJPB = reader.readString();
                    break;
                case 9:
                    message.Unk3300_CCOGBICMHKG = reader.readString();
                    break;
                case 1:
                    message.Unk3300_DJHKHEFPCDK = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): TrackingIOInfo {
        return TrackingIOInfo.deserialize(bytes);
    }
}
