/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: ViewCodexReq.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./CodexTypeData";
import * as pb_1 from "google-protobuf";
export class ViewCodexReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        type_data_list?: dependency_1.CodexTypeData[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [10], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("type_data_list" in data && data.type_data_list != undefined) {
                this.type_data_list = data.type_data_list;
            }
        }
    }
    get type_data_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.CodexTypeData, 10) as dependency_1.CodexTypeData[];
    }
    set type_data_list(value: dependency_1.CodexTypeData[]) {
        pb_1.Message.setRepeatedWrapperField(this, 10, value);
    }
    static fromObject(data: {
        type_data_list?: ReturnType<typeof dependency_1.CodexTypeData.prototype.toObject>[];
    }): ViewCodexReq {
        const message = new ViewCodexReq({});
        if (data.type_data_list != null) {
            message.type_data_list = data.type_data_list.map(item => dependency_1.CodexTypeData.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            type_data_list?: ReturnType<typeof dependency_1.CodexTypeData.prototype.toObject>[];
        } = {};
        if (this.type_data_list != null) {
            data.type_data_list = this.type_data_list.map((item: dependency_1.CodexTypeData) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.type_data_list.length)
            writer.writeRepeatedMessage(10, this.type_data_list, (item: dependency_1.CodexTypeData) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ViewCodexReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ViewCodexReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 10:
                    reader.readMessage(message.type_data_list, () => pb_1.Message.addToRepeatedWrapperField(message, 10, dependency_1.CodexTypeData.deserialize(reader), dependency_1.CodexTypeData));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ViewCodexReq {
        return ViewCodexReq.deserialize(bytes);
    }
}
