/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: WorktopInfo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class WorktopInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        option_list?: number[];
        is_guest_can_operate?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("option_list" in data && data.option_list != undefined) {
                this.option_list = data.option_list;
            }
            if ("is_guest_can_operate" in data && data.is_guest_can_operate != undefined) {
                this.is_guest_can_operate = data.is_guest_can_operate;
            }
        }
    }
    get option_list() {
        return pb_1.Message.getFieldWithDefault(this, 1, []) as number[];
    }
    set option_list(value: number[]) {
        pb_1.Message.setField(this, 1, value);
    }
    get is_guest_can_operate() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set is_guest_can_operate(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        option_list?: number[];
        is_guest_can_operate?: boolean;
    }): WorktopInfo {
        const message = new WorktopInfo({});
        if (data.option_list != null) {
            message.option_list = data.option_list;
        }
        if (data.is_guest_can_operate != null) {
            message.is_guest_can_operate = data.is_guest_can_operate;
        }
        return message;
    }
    toObject() {
        const data: {
            option_list?: number[];
            is_guest_can_operate?: boolean;
        } = {};
        if (this.option_list != null) {
            data.option_list = this.option_list;
        }
        if (this.is_guest_can_operate != null) {
            data.is_guest_can_operate = this.is_guest_can_operate;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.option_list.length)
            writer.writePackedUint32(1, this.option_list);
        if (this.is_guest_can_operate != false)
            writer.writeBool(2, this.is_guest_can_operate);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): WorktopInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new WorktopInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.option_list = reader.readPackedUint32();
                    break;
                case 2:
                    message.is_guest_can_operate = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): WorktopInfo {
        return WorktopInfo.deserialize(bytes);
    }
}
