// @generated by protobuf-ts 2.8.2 with parameter output_typescript
// @generated from protobuf file "WorldOwnerDailyTaskNotify.proto" (syntax proto3)
// tslint:disable
//
// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { DailyTaskInfo } from "./DailyTaskInfo";
/**
 * enum CmdId {
 *   option allow_alias = true;
 *   NONE = 0;
 *   CMD_ID = 193;
 *   ENET_CHANNEL_ID = 0;
 *   ENET_IS_RELIABLE = 1;
 *   IS_ALLOW_CLIENT = 1;
 * }
 *
 * @generated from protobuf message WorldOwnerDailyTaskNotify
 */
export interface WorldOwnerDailyTaskNotify {
    /**
     * @generated from protobuf field: uint32 filter_city_id = 4;
     */
    filterCityId: number;
    /**
     * @generated from protobuf field: repeated DailyTaskInfo task_list = 2;
     */
    taskList: DailyTaskInfo[];
    /**
     * @generated from protobuf field: uint32 finished_daily_task_num = 9;
     */
    finishedDailyTaskNum: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class WorldOwnerDailyTaskNotify$Type extends MessageType<WorldOwnerDailyTaskNotify> {
    constructor() {
        super("WorldOwnerDailyTaskNotify", [
            { no: 4, name: "filter_city_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "task_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DailyTaskInfo },
            { no: 9, name: "finished_daily_task_num", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<WorldOwnerDailyTaskNotify>): WorldOwnerDailyTaskNotify {
        const message = { filterCityId: 0, taskList: [], finishedDailyTaskNum: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<WorldOwnerDailyTaskNotify>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WorldOwnerDailyTaskNotify): WorldOwnerDailyTaskNotify {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 filter_city_id */ 4:
                    message.filterCityId = reader.uint32();
                    break;
                case /* repeated DailyTaskInfo task_list */ 2:
                    message.taskList.push(DailyTaskInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* uint32 finished_daily_task_num */ 9:
                    message.finishedDailyTaskNum = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WorldOwnerDailyTaskNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 filter_city_id = 4; */
        if (message.filterCityId !== 0)
            writer.tag(4, WireType.Varint).uint32(message.filterCityId);
        /* repeated DailyTaskInfo task_list = 2; */
        for (let i = 0; i < message.taskList.length; i++)
            DailyTaskInfo.internalBinaryWrite(message.taskList[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* uint32 finished_daily_task_num = 9; */
        if (message.finishedDailyTaskNum !== 0)
            writer.tag(9, WireType.Varint).uint32(message.finishedDailyTaskNum);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WorldOwnerDailyTaskNotify
 */
export const WorldOwnerDailyTaskNotify = new WorldOwnerDailyTaskNotify$Type();
