/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: WorldPlayerRTTNotify.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./PlayerRTTInfo";
import * as pb_1 from "google-protobuf";
export class WorldPlayerRTTNotify extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        player_rtt_list?: dependency_1.PlayerRTTInfo[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("player_rtt_list" in data && data.player_rtt_list != undefined) {
                this.player_rtt_list = data.player_rtt_list;
            }
        }
    }
    get player_rtt_list() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.PlayerRTTInfo, 1) as dependency_1.PlayerRTTInfo[];
    }
    set player_rtt_list(value: dependency_1.PlayerRTTInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        player_rtt_list?: ReturnType<typeof dependency_1.PlayerRTTInfo.prototype.toObject>[];
    }): WorldPlayerRTTNotify {
        const message = new WorldPlayerRTTNotify({});
        if (data.player_rtt_list != null) {
            message.player_rtt_list = data.player_rtt_list.map(item => dependency_1.PlayerRTTInfo.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            player_rtt_list?: ReturnType<typeof dependency_1.PlayerRTTInfo.prototype.toObject>[];
        } = {};
        if (this.player_rtt_list != null) {
            data.player_rtt_list = this.player_rtt_list.map((item: dependency_1.PlayerRTTInfo) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.player_rtt_list.length)
            writer.writeRepeatedMessage(1, this.player_rtt_list, (item: dependency_1.PlayerRTTInfo) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): WorldPlayerRTTNotify {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new WorldPlayerRTTNotify();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.player_rtt_list, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_1.PlayerRTTInfo.deserialize(reader), dependency_1.PlayerRTTInfo));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): WorldPlayerRTTNotify {
        return WorldPlayerRTTNotify.deserialize(bytes);
    }
}
